#!/usr/bin/env python3
"""Daily plan pipeline — Step 2 of the Controlled Drift system.

Pipeline (§1 of daily_list.md):
  1. Load active items from Anytype (Goals, Projects, Tasks, Strategies, Recurring-for-today)
  2. Run neglect query (items not surfaced in N days)
  3. Ask June for a capacity signal
  4. Feed all context to the daily_list.md prompt → LLM proposes order + frame
  5. Compute clock-time schedule (deterministic Python, never LLM)
  6. Present the negotiable plan in chat
  7. On confirm: update last_surfaced in Anytype, append to surface_log, log corrections

Run: python3 scripts/daily_plan.py
     (or invoke via /drift when June asks "what should I do today")
"""
import sys, os, datetime as dt, json

sys.path.insert(0, os.path.dirname(__file__))
from anytype_test import call
import gsdo_anytype as g
from datetime_seam import recurring_items_for_today
from neglect import query_neglected
from scheduler import schedule
from surface_log import log_surfaced_batch
from plan_corrections_log import log_correction


# --- Data loading -----------------------------------------------------------

def _prop_val(props_dict, key, kind):
    p = props_dict.get(key, {})
    return p.get(kind) if p else None


def load_active_items(sid):
    """Load Goals, Projects, Tasks (Active/Needs-Clarifying), Strategies from Anytype."""
    data = call("GET", f"/spaces/{sid}/objects?limit=200")[1].get("data", [])
    goals, projects, tasks, strategies, recurrings = [], [], [], [], []

    for obj in data:
        t = obj.get("type")
        tkey = t.get("key") if isinstance(t, dict) else t
        name = obj.get("name", "")
        oid = obj.get("id")
        props = {p.get("key"): p for p in obj.get("properties", [])}

        def pv(key, kind):
            return _prop_val(props, key, kind)

        if tkey == "gsdo_goal":
            status = (pv("gsdo_status", "select") or {}).get("name")
            if status in (None, "Active"):
                goals.append({"id": oid, "name": name,
                               "reaching_for": pv("gsdo_reaching_for", "text"),
                               "context": pv("gsdo_context", "text")})

        elif tkey == "gsdo_project":
            # Name-based lookup for the newer Engagement field (key generated by Anytype, not predictable).
            props_by_name = {p.get("name"): p for p in obj.get("properties", [])}
            def pvn(nm, kind, _pbn=props_by_name):
                p = _pbn.get(nm, {})
                return p.get(kind) if p else None

            engagement_tag = pvn("Engagement", "select") or {}
            engagement = engagement_tag.get("name") if isinstance(engagement_tag, dict) else None

            if engagement == "Done":
                continue  # Done projects are invisible in the daily plan

            projects.append({"id": oid, "name": name,
                              "context": pv("gsdo_context", "text"),
                              "affective": pv("gsdo_affective", "text"),
                              "deadline": pv("gsdo_deadline", "date"),
                              "engagement": engagement,
                              "engagement_notes": pvn("Engagement notes", "text")})

        elif tkey == "task":
            status_tag = pv("status", "select") or {}
            status = status_tag.get("name") if isinstance(status_tag, dict) else status_tag
            if status in (None, "Active", "Needs Clarifying"):
                done = pv("done", "checkbox")
                if done:
                    continue
                access_tags = pv("gsdo_access", "multi_select") or []
                access = [t.get("name") for t in access_tags if isinstance(t, dict)]
                linked_proj_objs = pv("linked_projects", "object") or []
                linked_projects = [lp.get("name") for lp in linked_proj_objs
                                   if isinstance(lp, dict) and lp.get("name")]
                tasks.append({"id": oid, "name": name,
                               "status": status,
                               "duration_min": pv("gsdo_duration_min", "number"),
                               "affective": pv("gsdo_affective", "text"),
                               "access": access,
                               "blocked_on": pv("gsdo_blocked_on", "text"),
                               "context": pv("gsdo_context", "text"),
                               "linked_projects": linked_projects})

        elif tkey == "gsdo_strategy":
            status = (pv("gsdo_status", "select") or {}).get("name")
            if status in (None, "Active"):
                strategies.append({"id": oid, "name": name,
                                    "what_for": pv("gsdo_what_for", "text"),
                                    "context": pv("gsdo_context", "text")})

        elif tkey == "gsdo_recurring":
            recurrings.append(obj)

    today_recurrings = recurring_items_for_today(recurrings)
    return goals, projects, tasks, strategies, today_recurrings


def load_neglected(days=3):
    """Items not surfaced in N days (Tasks + Projects)."""
    try:
        return query_neglected(days=days)
    except Exception as e:
        print(f"[warn] neglect query failed: {e}", file=sys.stderr)
        return []


# --- Context formatting for the LLM ----------------------------------------

def format_context(goals, projects, tasks, strategies, today_recurrings, neglected, capacity):
    """Build the context block that gets injected into the daily_list.md prompt."""
    lines = []

    lines.append(f"Current time: {dt.datetime.now().strftime('%A %B %d, %Y — %I:%M %p')}")
    lines.append(f"Capacity signal: {capacity or '(none given)'}")
    lines.append("")

    if strategies:
        lines.append("## Active strategies")
        for s in strategies:
            desc = s.get("what_for") or s.get("context") or ""
            lines.append(f"- {s['name']}" + (f": {desc}" if desc else ""))
        lines.append("")

    if goals:
        lines.append("## Active goals")
        for g_ in goals:
            rf = g_.get("reaching_for") or ""
            lines.append(f"- {g_['name']}" + (f" (reaching for: {rf})" if rf else ""))
        lines.append("")

    if projects:
        lines.append("## Active projects")
        lines.append("(engagement: Sprint/Hyperfixation → priority real estate; Steady → daily move;"
                     " Backburner → only if neglected; Needs Clarifying → flag it)")
        for p in projects:
            eng = p.get("engagement") or "Steady"
            eng_notes = p.get("engagement_notes") or ""
            line = f"- {p['name']} [{eng}]"
            if eng_notes:
                line += f" | {eng_notes}"
            ctx = p.get("context") or ""
            aff = p.get("affective") or ""
            if ctx:
                line += f" | context: {ctx}"
            if aff:
                line += f" | affective: {aff}"
            lines.append(line)
        lines.append("")

    if tasks:
        lines.append("## Active tasks by project/thread")
        lines.append("(The LLM should organize the plan by these project/thread groupings,")
        lines.append(" NOT by activity category like 'writing' or 'admin'.)")

        def _task_extras(t):
            extras = []
            if t.get("status") == "Needs Clarifying":
                extras.append("needs clarifying")
            if t.get("blocked_on"):
                extras.append(f"blocked on: {t['blocked_on']}")
            if t.get("duration_min"):
                extras.append(f"~{t['duration_min']}min")
            if t.get("affective"):
                extras.append(f"affective: {t['affective']}")
            if t.get("access"):
                extras.append(f"access: {', '.join(t['access'])}")
            return f" ({'; '.join(extras)})" if extras else ""

        # Group tasks by project. A task linked to multiple projects appears under each.
        project_tasks: dict = {}
        no_project = []
        for t in tasks:
            projs = t.get("linked_projects") or []
            if projs:
                for pn in projs:
                    project_tasks.setdefault(pn, []).append(t)
            else:
                no_project.append(t)

        for pname, ptasks in project_tasks.items():
            lines.append(f"- **{pname}**")
            for t in ptasks:
                lines.append(f"  - {t['name']}{_task_extras(t)}")
        if no_project:
            lines.append("- **[No project]**")
            for t in no_project:
                lines.append(f"  - {t['name']}{_task_extras(t)}")
        lines.append("")

    if today_recurrings:
        lines.append("## Recurring items scheduled today")
        for r in today_recurrings:
            lines.append(f"- {r['name']} at {r['fixed_time'].strftime('%H:%M')}")
        lines.append("")

    # Only show in neglected: items that were previously surfaced but have gone stale.
    # "Never surfaced" items are already in the active lists above — showing them twice
    # is noise (the system is new and everything looks neglected on first run).
    active_names = {t["name"] for t in tasks} | {p["name"] for p in projects}
    neglected_stale = [n for n in neglected
                       if n.get("last_surfaced") is not None
                       and n["name"] not in {r["name"] for r in today_recurrings}
                       and n["name"] not in active_names]
    if neglected_stale:
        lines.append("## Items not surfaced recently (resurfacing)")
        for n in neglected_stale:
            ls = n.get("last_surfaced")
            lines.append(f"- {n['name']} (last seen {ls.date()})")
        lines.append("")

    return "\n".join(lines)


# --- Clock-time schedule + time-block formatting ----------------------------

# Default meal anchors — injected when no meal-type Recurring item exists.
# June can override by adding a Recurring "Lunch" item in Anytype.
_DEFAULT_MEALS = [
    {"name": "Lunch", "hour": 12, "minute": 0, "duration_min": 30},
]

def default_meal_anchors(today_recurrings, start_time):
    """Return default meal anchor items not already covered by a Recurring item."""
    existing = {r["name"].lower() for r in today_recurrings}
    anchors = []
    today = start_time.date()
    for meal in _DEFAULT_MEALS:
        if not any(meal["name"].lower() in name for name in existing):
            fixed = dt.datetime.combine(today, dt.time(meal["hour"], meal["minute"]))
            if fixed > start_time:
                anchors.append({
                    "id": None,
                    "name": meal["name"],
                    "fixed_time": fixed,
                    "duration_min": meal["duration_min"],
                    "_default_anchor": True,
                })
    return anchors


def build_schedule(llm_ordered_items, all_anchors, start_time=None):
    """Merge LLM-proposed task order with fixed anchors (Recurring + meal defaults).
    llm_ordered_items: list of {"name", "duration_min", ...} in proposed order.
    all_anchors: today_recurrings + default_meal_anchors (both have fixed_time).
    Returns scheduled list with start_time/end_time on each item.
    """
    start_time = start_time or dt.datetime.now().replace(second=0, microsecond=0)
    existing_names = {it["name"] for it in llm_ordered_items}
    all_items = list(llm_ordered_items) + [
        {**r, "fixed_time": r["fixed_time"]} for r in all_anchors
        if r["name"] not in existing_names
    ]
    return schedule(all_items, start_time)


def _block_label(hour):
    if hour < 12:
        return "Morning"
    elif hour < 14:
        return "Midday"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"


def format_schedule_blocks(scheduled):
    """Group the Python-computed schedule into named time blocks.

    Claude reads this and adds narrative framing for each block, producing
    one integrated plan. Python owns times and order; Claude owns framing.
    """
    from collections import OrderedDict
    blocks: OrderedDict = OrderedDict()
    for item in scheduled:
        start = item.get("start_time")
        if not start:
            continue
        label = _block_label(start.hour)
        blocks.setdefault(label, []).append(item)

    def _fmt_time(t):
        # "9:15 AM" not "09:15 AM"
        return t.strftime("%I:%M %p").lstrip("0")

    lines = []
    lines.append("## Pre-computed clock schedule — your output skeleton")
    lines.append("Python owns times and order. Your job:")
    lines.append("  1. Write 1-2 sentence narrative framing for each block (what it's for, energy note).")
    lines.append("  2. List each item with its clock time verbatim.")
    lines.append("  3. Produce ONE integrated plan — not a narrative followed by a separate schedule.")
    lines.append("  Do not change times or reorder items.")
    lines.append("")

    for label, items in blocks.items():
        b_start = items[0]["start_time"]
        b_end = items[-1].get("end_time") or items[-1]["start_time"]
        lines.append(f"### {label} ({_fmt_time(b_start)} – {_fmt_time(b_end)})")
        for item in items:
            s = item.get("start_time")
            e = item.get("end_time")
            time_str = f"{_fmt_time(s)} – {_fmt_time(e)}" if s and e else "?"
            dur = item.get("duration_min")
            dur_str = f" (~{dur}min)" if dur else ""
            lines.append(f"  {time_str} | {item['name']}{dur_str}")
        lines.append("")

    return "\n".join(lines)


# --- Anytype writes ----------------------------------------------------------

def update_last_surfaced(sid, item_ids):
    """Write today's date to last_surfaced on each item."""
    today_iso = dt.date.today().isoformat()
    ls_prop = g.find_property("Last surfaced")
    if ls_prop is None:
        print("[warn] 'Last surfaced' property not found — skipping update", file=sys.stderr)
        return
    for oid in item_ids:
        call("PATCH", f"/spaces/{sid}/objects/{oid}",
             {"properties": [{"key": ls_prop["key"], "date": today_iso}]})


# --- Main -------------------------------------------------------------------

def run():
    sid = g.get_space_id()
    goals, projects, tasks, strategies, today_recurrings = load_active_items(sid)
    neglected = load_neglected()

    print("\n=== Controlled Drift — Daily Plan ===\n")
    try:
        capacity = input("Capacity signal (one word/phrase, or Enter to skip): ").strip()
    except EOFError:
        capacity = ""

    # Compute the clock-time schedule FIRST so it can be part of the LLM's context.
    # Python owns times and order; the LLM adds narrative framing around the skeleton.
    start_time = dt.datetime.now().replace(second=0, microsecond=0)
    meals = default_meal_anchors(today_recurrings, start_time)
    all_anchors = today_recurrings + meals
    task_items = [{"name": t["name"], "duration_min": t.get("duration_min")} for t in tasks]
    scheduled = build_schedule(task_items, all_anchors, start_time)
    schedule_block = format_schedule_blocks(scheduled)

    context_block = format_context(
        goals, projects, tasks, strategies, today_recurrings, neglected, capacity)

    # Combine context + schedule skeleton so the LLM receives both
    full_context = context_block + "\n" + schedule_block

    # Read the prompt template
    prompt_path = os.path.join(os.path.dirname(__file__), "..", "prompts", "daily_list.md")
    with open(prompt_path) as f:
        prompt_template = f.read()

    # Inject context + schedule into prompt
    prompt = prompt_template.replace(
        "- Capacity signal: [what June said about today, or empty]",
        f"- Capacity signal: {capacity or '(none given)'}"
    ).replace(
        "- Active tasks/projects/goals/strategies: [via MCP]",
        f"- Active tasks/projects/goals/strategies:\n\n{full_context}"
    ).replace(
        "- Current time: [system time, for the downstream scheduler]",
        f"- Current time: {start_time.strftime('%A %B %d, %Y — %I:%M %p')}"
    )

    print("\n--- Context + schedule loaded. Prompt ready for LLM. ---")
    print(f"Goals: {len(goals)}  Projects: {len(projects)}  Tasks: {len(tasks)}  "
          f"Strategies: {len(strategies)}  Recurring today: {len(today_recurrings)}  "
          f"Meals injected: {len(meals)}  Neglected: {len(neglected)}")
    print("\nFull context (injected into daily_list.md prompt):\n")
    print(full_context)
    print("\n(In the /drift skill flow, the LLM receives this prompt and returns the")
    print(" integrated time-block plan with narrative framing. Run via /drift.)")

    try:
        confirm = input("\nConfirm and update last_surfaced? [y/N]: ").strip().lower()
    except EOFError:
        confirm = "n"
    if confirm == "y":
        # Only write to Anytype for real objects — exclude default meal anchors (no id)
        anytype_recurrings = [r for r in all_anchors if r.get("id")]
        surfaced_ids = [t["id"] for t in tasks] + [r["id"] for r in anytype_recurrings]
        update_last_surfaced(sid, surfaced_ids)
        log_surfaced_batch(
            [{"id": t["id"], "name": t["name"], "type": "task"} for t in tasks] +
            [{"id": r["id"], "name": r["name"], "type": "recurring"} for r in anytype_recurrings]
        )
        for item in scheduled:
            if item.get("start_time") and item.get("id"):
                log_correction("initial_placement", None,
                               {"name": item["name"],
                                "start": item["start_time"].isoformat(),
                                "end": item.get("end_time", "").isoformat() if item.get("end_time") else None})
        print(f"✓ Updated last_surfaced on {len(surfaced_ids)} items. Schedule logged.")


if __name__ == "__main__":
    run()
