#!/usr/bin/env python3
"""Daily plan pipeline — Step 2 of the Controlled Drift system.

Pipeline (§1 of daily_list.md):
  1. Load active items from Anytype (Goals, Projects, Tasks, Strategies, Recurring-for-today)
  2. Run neglect query (items not surfaced in N days)
  3. Ask June for a capacity signal
  4. Feed all context to the daily_list.md prompt → LLM proposes order + frame
  5. Compute clock-time schedule (deterministic Python, never LLM)
  6. Present the negotiable plan in chat
  7. On confirm: update last_surfaced in Anytype, append to surface_log, log corrections

Run: python3 scripts/daily_plan.py
     (or invoke via /drift when June asks "what should I do today")
"""
import sys, os, datetime as dt, json

sys.path.insert(0, os.path.dirname(__file__))
from anytype_test import call
import gsdo_anytype as g
import grain
import chunk_log
from datetime_seam import recurring_items_for_today
from neglect import active_untouched
from scheduler import schedule, DEFAULT_DURATION_MIN
from surface_log import log_surfaced_batch
from plan_corrections_log import log_correction


# --- Data loading -----------------------------------------------------------

def _prop_val(props_dict, key, kind):
    p = props_dict.get(key, {})
    return p.get(kind) if p else None


def _inherit_is_workstream(projects):
    """Propagate is_workstream down the parent chain: a subproject under a workstream is
    workstream work even if its own checkbox is unset. Mirrors the Side-inheritance walk and
    orient_map's `_is_workstream` ancestor logic. Idempotent; safe against parent cycles."""
    by_id = {p["id"]: p for p in projects}
    for p in projects:
        if p.get("is_workstream"):
            continue
        seen, cur = set(), p
        while cur.get("parent_project_id") in by_id and cur["id"] not in seen:
            seen.add(cur["id"])
            cur = by_id[cur["parent_project_id"]]
            if cur.get("is_workstream"):
                p["is_workstream"] = True
                break


def load_active_items(sid):
    """Load Goals, Projects, Tasks (Active/Needs-Clarifying), Strategies from Anytype."""
    data = g.fetch_all_objects(sid)
    goals, projects, tasks, strategies, recurrings = [], [], [], [], []
    # Project id -> name, for resolving a task's Linked Projects relation. That relation reads
    # back as a list of id STRINGS (not dicts), under the "objects" value — so it must be
    # resolved by id here, not read as dicts. (Fixes a long-standing empty-linked_projects bug.)
    proj_id_to_name = {o["id"]: o.get("name") for o in data
                       if isinstance(o.get("type"), dict) and o["type"].get("key") == "gsdo_project"}
    goal_id_to_name = {o["id"]: o.get("name") for o in data
                       if isinstance(o.get("type"), dict) and o["type"].get("key") == "gsdo_goal"}

    for obj in data:
        t = obj.get("type")
        tkey = t.get("key") if isinstance(t, dict) else t
        name = obj.get("name", "")
        oid = obj.get("id")
        props = {p.get("key"): p for p in obj.get("properties", [])}

        def pv(key, kind):
            return _prop_val(props, key, kind)

        if tkey == "gsdo_goal":
            status = (pv("gsdo_goal_status", "select") or {}).get("name")
            if status in (None, "Active"):
                props_by_name = {p.get("name"): p for p in obj.get("properties", [])}
                def pvn_g(nm, kind, _pbn=props_by_name):
                    p = _pbn.get(nm, {})
                    return p.get(kind) if p else None
                goals.append({"id": oid, "name": name,
                               "reaching_for": pv("gsdo_reaching_for_(text)", "text"),
                               "resolution_condition": pvn_g("Resolution condition", "text"),
                               "engagement": (pvn_g("Goal engagement", "select") or {}).get("name"),
                               "context": pv("gsdo_context", "text")})

        elif tkey == "gsdo_project":
            # Name-based lookup for the newer Engagement field (key generated by Anytype, not predictable).
            props_by_name = {p.get("name"): p for p in obj.get("properties", [])}
            def pvn(nm, kind, _pbn=props_by_name):
                p = _pbn.get(nm, {})
                return p.get(kind) if p else None

            engagement_tag = pvn("Engagement", "select") or {}
            engagement = engagement_tag.get("name") if isinstance(engagement_tag, dict) else None

            if engagement == "Done":
                continue  # Done projects are invisible in the daily plan

            # Side: Obligation / Wellbeing / Fun / hobby — June's three categories, read by display
            # name like Engagement (Anytype-generated key). "Fun / hobby" = self-directed
            # creative/dev work held out of the daily plan; Obligation (must-do life+career) and
            # Wellbeing (walks, rest, care) both stay in the day.
            side_tag = pvn("Side", "select") or {}
            side = side_tag.get("name") if isinstance(side_tag, dict) else None

            # Goal link -> goal_name (2026-07-14 fix): the loader used to drop this relation, so
            # every project arrived goal-less and the "how does today advance her goals" instruction
            # had nothing to work from (plan_input_seam_design.md, diagnosis 3). Real fixed key.
            goal_ids = pv("gsdo_goal_link", "objects") or []
            goal_id = goal_ids[0] if goal_ids else None
            goal_name = goal_id_to_name.get(goal_id) if goal_id else None

            parent_proj_ids = pv("gsdo_parent_project", "objects") or []
            parent_project_id = parent_proj_ids[0] if parent_proj_ids else None

            projects.append({"id": oid, "name": name,
                              "reaching_for": pv("gsdo_reaching_for", "text"),
                              "context": pv("gsdo_context", "text"),
                              "affective": pv("gsdo_affective", "text"),
                              "deadline": pv("gsdo_deadline", "date"),
                              "engagement": engagement,
                              "engagement_notes": pvn("Engagement notes", "text"),
                              "side": side,
                              "goal_id": goal_id,
                              "goal_name": goal_name,
                              "is_workstream": bool((props.get("is_workstream") or {}).get("checkbox")),
                              # Block chunk length (minutes). Read BY NAME — Anytype auto-generated
                              # its key (block_chunk_min, no gsdo_ prefix), like Engagement/Side.
                              "chunk_min": pvn("Block chunk min", "number"),
                              "parent_project_id": parent_project_id})

    # Side inheritance (June, 2026-07-13): a subproject's Side is read from its nearest
    # ancestor when unset, rather than duplicating the parent's value onto every subproject.
    # parent_project_id was already captured per project above; this just resolves the chain.
    _by_id = {p["id"]: p for p in projects}
    for p in projects:
        seen, cur = set(), p
        while cur.get("side") is None and cur.get("parent_project_id") in _by_id and cur["id"] not in seen:
            seen.add(cur["id"])
            cur = _by_id[cur["parent_project_id"]]
        if p.get("side") is None and cur is not p:
            p["side"] = cur.get("side")

    # is_workstream inheritance (2026-07-14): a subproject under a workstream IS workstream
    # work, even if its own checkbox is unset — mirror the Side walk so the daily-plan grain
    # classifier (grain.classify) filters the whole subtree out of block-grain, as orient_map
    # already does via _is_workstream's ancestor walk.
    _inherit_is_workstream(projects)

    # Attach each project's step arc HERE, where the raw `data` (which keeps done tasks, unlike
    # the daily-plan task list) and proj_id_to_name both live — so build_context can emit a block's
    # arc with no re-fetch and no return-signature change. A block reads project["arc"]:
    # non-empty → opens to that arc; None → a bare chunk. (display_grain_design.md decision 5.)
    for p in projects:
        p["arc"] = grain.project_arc(p["name"], data, proj_id_to_name)

    for obj in data:
        t = obj.get("type")
        tkey = t.get("key") if isinstance(t, dict) else t
        name = obj.get("name", "")
        oid = obj.get("id")
        props = {p.get("key"): p for p in obj.get("properties", [])}

        def pv(key, kind):
            return _prop_val(props, key, kind)

        if tkey == "task":
            # The system's task status lives in the GSDO `gsdo_task_status` select (Active /
            # Ready / Done / Parked / …) — NOT the built-in `status`, which is vestigial and
            # always empty. Reading the built-in one silently included Done/Parked tasks in the
            # plan (they never got filtered). Read the property the rest of the system writes.
            status_tag = pv("gsdo_task_status", "select") or {}
            status = status_tag.get("name") if isinstance(status_tag, dict) else status_tag
            if status in (None, "Active", "Ready", "Needs Clarifying"):
                done = pv("done", "checkbox")
                if done:
                    continue
                # The tags live under the key `gsdo_access_conditions` (display "Access
                # conditions") — NOT `gsdo_access`. Reading the wrong key meant every task's
                # access tags came back empty since they were seeded (2026-07), so capacity/
                # access-aware planning had no signal to act on. (Fixed 2026-07-11.)
                access_tags = pv("gsdo_access_conditions", "multi_select") or []
                access = [t.get("name") for t in access_tags if isinstance(t, dict)]
                # The relation reads back under "objects" as a list of id strings (or dicts).
                # Resolve each to the current project name (rename-safe, by id).
                linked_raw = pv("linked_projects", "objects") or []
                linked_projects = []
                for x in linked_raw:
                    pid = x.get("id") if isinstance(x, dict) else x
                    nm = proj_id_to_name.get(pid)
                    if nm:
                        linked_projects.append(nm)
                tasks.append({"id": oid, "name": name,
                               "status": status,
                               "duration_min": pv("gsdo_duration_min", "number"),
                               "affective": pv("gsdo_affective", "text"),
                               "access": access,
                               "blocked_on": pv("gsdo_blocked_on", "text"),
                               "context": pv("gsdo_context", "text"),
                               # Built-in Due date (the DEADLINE — distinct from Scheduled, the
                               # start-considering date). The within-thread pick reads this as the
                               # nearest-deadline signal; raw Anytype date value, None when unset.
                               "due_date": pv("due_date", "date"),
                               "linked_projects": linked_projects})

        elif tkey == "gsdo_strategy":
            status = (pv("gsdo_status", "select") or {}).get("name")
            if status in (None, "Active"):
                # "Applies when" has an Anytype-generated key — read by display name, like Side.
                s_pbn = {p.get("name"): p for p in obj.get("properties", [])}
                aw_sel = (s_pbn.get("Applies when", {}) or {}).get("select") or {}
                applies_when = aw_sel.get("name") if isinstance(aw_sel, dict) else None
                strategies.append({"id": oid, "name": name,
                                    "what_for": pv("gsdo_what_for", "text"),
                                    "context": pv("gsdo_context", "text"),
                                    "applies_when": applies_when or "Always"})

        elif tkey == "gsdo_recurring":
            recurrings.append(obj)

    today_recurrings = recurring_items_for_today(recurrings)

    # Focus Period + resolved calendar facts — loaded HERE, the one seam both the terminal
    # (run) and live (plan_generate.build_context) paths call, so the feature reaches every
    # surface from one place, not just the terminal path. Reuses `data` — no second fetch.
    import focus_period as fp
    today = dt.date.today()
    period = fp.load_active_focus_period(data, today)
    if period:
        # Resolve foreground/paused project ids -> current names from the authoritative
        # projects list (rename-safe: the stored link is the id; the name is resolved live).
        # The relation reads back as id strings, so the name comes from here, not the stored value.
        id_to_name = {p["id"]: p["name"] for p in projects}
        def _resolve(pairs):
            return [id_to_name.get(i) or n for i, n in pairs if (i in id_to_name) or n]
        period["foreground"] = _resolve(period.get("foreground_pairs", []))
        period["paused"] = _resolve(period.get("paused_pairs", []))
    weekly_off = fp.load_day_off_defaults()
    period_ctx = {"period": period,
                  "is_off": fp.is_day_off(period, weekly_off, today),
                  "in_window": fp.in_availability_window(period, today)}
    return goals, projects, tasks, strategies, today_recurrings, period_ctx


def load_neglected(days=16):
    # 16 days — June's calibration 2026-07-12, aligned with the upkeep-strategy threshold;
    # per-priority calibration is the future Strategy-driven version.
    """Active projects (Steady/Sprint/Hyperfixation) that aren't getting finished. Switched
    2026-07-13 from the dormant/Backburner-by-last-surfaced query to the active-untouched-by-
    last-COMPLETION cohort: an active project resurfaces every day regardless, so "neglect"
    has to mean not-getting-worked-on, not not-surfaced; dormant resurfacing is a separate,
    later cohort (neglect.dormant_neglected), intentionally unwired here for now."""
    try:
        return active_untouched(days=days)
    except Exception as e:
        print(f"[warn] neglect query failed: {e}", file=sys.stderr)
        return []


# --- Context formatting for the LLM ----------------------------------------

# --- Capacity → which triggered strategies activate --------------------------
# A capacity signal (the "Low energy" button sends "low-energy"; free text is matched loosely)
# maps to a STATE. A Strategy whose "Applies when" state matches gets pulled in as a firm
# directive; strategies marked "Always" are read every day as before. This is the wiring that
# makes capacity actually reshape the plan (June, 2026-07-11) — it points a state at HER authored
# rule instead of a vague "capacity is low" line the model could ignore.
_LOW_MARKERS = ("low-energy", "low energy", "tired", "exhausted", "drained", "wiped",
                "no energy", "low spoons", "lying down", "in bed", "in pain", "hurting",
                "rough", "bad day", "overwhelmed", "burnt out", "burned out", "depleted")
_APPLIES_TO_LEVEL = {"Low energy": "low"}  # extend as June names more states (Sprint→high, …)


def capacity_level(capacity):
    """Map a capacity signal to a state: 'low' or 'normal'. Deterministic keyword read;
    'normal' when unclear, so no triggered strategy fires unless the signal is clear."""
    if not capacity:
        return "normal"
    c = str(capacity).lower()
    return "low" if any(m in c for m in _LOW_MARKERS) else "normal"


def format_context(goals, projects, tasks, strategies, today_recurrings, neglected, capacity,
                   period=None, is_off=False, in_window=False):
    """Build the context block that gets injected into the daily_list.md prompt."""
    lines = []

    lines.append(f"Current time: {dt.datetime.now().strftime('%A %B %d, %Y — %I:%M %p')}")
    lines.append(f"Capacity signal: {capacity or '(none given)'}")
    lines.append("")

    if period:
        lines.append("## TODAY'S FOCUS PERIOD — June authored this in her own words. It is the "
                     "authoritative instruction for composing today's plan: follow it, and let it "
                     "govern the order, the selection, and how much fits — over any generic default. "
                     "A gentle/low-spoon intent means fewer items, lighter moves, and deferring "
                     "demanding work to still_here.")
        lines.append(f"- {period.get('name') or '(unnamed period)'}")
        if period.get("intent"):
            lines.append(f"- June's intent, in her words (honor this literally): {period['intent']}")
        if is_off:
            lines.append("- Today is marked a DAY OFF — plan rest/protected time, not survival "
                         "work (unless June says otherwise or a hard deadline conflicts).")
        if in_window and period.get("availability_note"):
            lines.append(f"- Availability today: {period['availability_note']}")
        if period.get("foreground"):
            lines.append(f"- Foreground this period: {', '.join(period['foreground'])}")
        if period.get("paused"):
            lines.append(f"- Paused this period: {', '.join(period['paused'])}")
        if period.get("days_off_error"):
            lines.append("- A day-off setting couldn't be read — check it; today was planned "
                         "as a normal work day.")
        lines.append("")

    # Split strategies: always-on (read every day) vs. state-triggered (only when their state
    # is active). A triggered strategy is injected as a FIRM directive so it actually reshapes
    # the plan, rather than sitting in the passive list the model tends to under-weight.
    level = capacity_level(capacity)
    always_strats = [s for s in strategies if (s.get("applies_when") or "Always") == "Always"]
    triggered_strats = [s for s in strategies
                        if level != "normal" and _APPLIES_TO_LEVEL.get(s.get("applies_when")) == level]

    if triggered_strats:
        lines.append(f"## TODAY'S CAPACITY IS {level.upper()} — apply these as FIRM constraints on "
                     "the whole plan (June authored them for exactly this state; honor them over the "
                     "usual ordering):")
        for s in triggered_strats:
            parts = [s["name"]]
            if s.get("what_for"): parts.append(s["what_for"])
            if s.get("context"): parts.append(s["context"])
            lines.append("- " + " — ".join(parts))
        lines.append("")

    if always_strats:
        lines.append("## Active strategies")
        for s in always_strats:
            desc = s.get("what_for") or s.get("context") or ""
            lines.append(f"- {s['name']}" + (f": {desc}" if desc else ""))
        lines.append("")

    if goals:
        lines.append("## Active goals")
        lines.append("(engagement: Steady → normal; Backburner → note but de-emphasize. What's "
                     "elevated right now comes from the Focus Period foreground, not the tag.)")
        for g_ in goals:
            eng = g_.get("engagement") or "Steady"
            line = f"- {g_['name']} [{eng}]"
            rf = g_.get("reaching_for") or ""
            rc = g_.get("resolution_condition") or ""
            ctx = g_.get("context") or ""
            if rf:
                line += f" | reaching for: {rf}"
            if rc:
                line += f" | resolved when: {rc}"
            if ctx:
                line += f" | context: {ctx}"
            lines.append(line)
        lines.append("")

    if projects:
        lines.append("## Active projects")
        lines.append("(engagement: Steady → a normal daily move; Backburner → only if neglected;"
                     " Needs Clarifying → flag it. What's elevated right now is set by the Focus"
                     " Period foreground, not the engagement tag — don't inflate a project's space"
                     " just for its label.)")
        lines.append("(sub-projects are indented under their parent)")

        fg = set((period or {}).get("foreground") or [])
        paused = set((period or {}).get("paused") or [])

        def _project_line(p, indent=""):
            eng = p.get("engagement") or "Steady"
            eng_notes = p.get("engagement_notes") or ""
            line = f"{indent}- {p['name']} [{eng}]"
            if p.get("side"):
                line += f" | side: {p['side']}"
            if p["name"] in paused:
                line += " [paused this period]"
            if eng_notes:
                line += f" | {eng_notes}"
            rf = p.get("reaching_for") or ""
            ctx = p.get("context") or ""
            aff = p.get("affective") or ""
            if rf:
                line += f" | reaching for: {rf}"
            if ctx:
                line += f" | context: {ctx}"
            if aff:
                line += f" | affective: {aff}"
            return line

        # Build tree: top-level projects first, then sub-projects nested under parent.
        # Foreground projects (period override) sort to the front — a display nicety; the
        # real reprioritization is in task selection (plan_generate.select_and_order_tasks).
        project_by_id = {p["id"]: p for p in projects}
        top_level = [p for p in projects if not p.get("parent_project_id")]
        top_level.sort(key=lambda p: (p["name"] not in fg, p["name"]))
        children_by_parent: dict = {}
        for p in projects:
            pid = p.get("parent_project_id")
            if pid:
                children_by_parent.setdefault(pid, []).append(p)

        for p in top_level:
            lines.append(_project_line(p))
            for child in children_by_parent.get(p["id"], []):
                lines.append(_project_line(child, indent="  "))
        # Orphaned sub-projects (parent not in active list) — show flat with note
        for p in projects:
            pid = p.get("parent_project_id")
            if pid and pid not in project_by_id:
                lines.append(_project_line(p) + " [sub-project]")
        lines.append("")

    if tasks:
        lines.append("## Active tasks by project/thread")
        lines.append("(The LLM should organize the plan by these project/thread groupings,")
        lines.append(" NOT by activity category like 'writing' or 'admin'.)")

        def _task_extras(t):
            extras = []
            if t.get("status") == "Needs Clarifying":
                extras.append("needs clarifying")
            if t.get("blocked_on"):
                extras.append(f"blocked on: {t['blocked_on']}")
            if t.get("duration_min"):
                extras.append(f"~{t['duration_min']}min")
            if t.get("affective"):
                extras.append(f"affective: {t['affective']}")
            if t.get("access"):
                extras.append(f"access: {', '.join(t['access'])}")
            return f" ({'; '.join(extras)})" if extras else ""

        # Group tasks by project. A task linked to multiple projects appears under each.
        project_tasks: dict = {}
        no_project = []
        for t in tasks:
            projs = t.get("linked_projects") or []
            if projs:
                for pn in projs:
                    project_tasks.setdefault(pn, []).append(t)
            else:
                no_project.append(t)

        # Split the hierarchy into two labeled categories so the model knows which kind each is
        # (display_grain_design REVISION, decision C): "block-organized work" (ongoing projects it
        # orders as a 'Work on X' block; their tasks are the arc) vs "daily tasks" (discrete chores
        # + standalone actions it checks off). Category = grain.classify; excluded projects omitted.
        proj_by_name = {p["name"]: p for p in projects}

        def _grain_of(pname):
            p = proj_by_name.get(pname)
            return grain.classify(p) if p else "task"        # no-project → discrete, daily-side

        block_projects = {pn: ts for pn, ts in project_tasks.items() if _grain_of(pn) == "block"}
        daily_projects = {pn: ts for pn, ts in project_tasks.items() if _grain_of(pn) == "task"}

        if block_projects:
            lines.append("### Block-organized work — ongoing projects. Order each as ONE 'Work on X'"
                         " block; the tasks under it are its arc (do not enumerate them as separate"
                         " plan items).")
            for pname, ptasks in block_projects.items():
                lines.append(f"- **{pname}**")
                for t in ptasks:
                    lines.append(f"  - {t['name']}{_task_extras(t)}")
        if daily_projects or no_project:
            lines.append("### Daily tasks — discrete chores + standalone actions. Surface each as its"
                         " own task to check off.")
            for pname, ptasks in daily_projects.items():
                lines.append(f"- **{pname}**")
                for t in ptasks:
                    lines.append(f"  - {t['name']}{_task_extras(t)}")
            if no_project:
                lines.append("- **[No project]**")
                for t in no_project:
                    lines.append(f"  - {t['name']}{_task_extras(t)}")
        lines.append("")

    if today_recurrings:
        lines.append("## Recurring items scheduled today")
        for r in today_recurrings:
            lines.append(f"- {r['name']} at {r['fixed_time'].strftime('%H:%M')}")
        lines.append("")

    # The "not getting to" section: ACTIVE projects (Steady/Sprint/Hyperfixation) June keeps
    # seeing but isn't FINISHING anything in. `neglected` is now the active-untouched cohort
    # (neglect.active_untouched: stale by last-COMPLETION, not last-surface — an active project
    # surfaces a move every day, so "not surfaced lately" could never catch it). The model can
    # gently offer to bring one back (prompt §3). Backburner/unset/Open going quiet is EXPECTED
    # and handled by the gate, not surfaced here. `last_completed` is the datetime the cohort
    # flagged on (None when the project has never had a completion).
    active_engagement = {"Steady", "Sprint", "Hyperfixation"}
    active_project_names = {p["name"] for p in projects
                            if p.get("engagement") in active_engagement}
    today_recurring_names = {r["name"] for r in today_recurrings}

    def _in_active_project(n):
        if n.get("type") == "project":
            return n["name"] in active_project_names
        return any(pn in active_project_names for pn in (n.get("linked_projects") or []))

    neglected_stale = [n for n in neglected
                       if n["name"] not in today_recurring_names
                       and _in_active_project(n)]
    if neglected_stale:
        lines.append("## Active projects you're not getting to")
        lines.append("(These are active projects where nothing has been finished in a while. "
                     "Gently offer to bring one back into focus if it fits — don't nag.)")
        for n in neglected_stale:
            lc = n.get("last_completed")
            when = f"last finished something {lc.date()}" if lc else "nothing finished in it yet"
            lines.append(f"- {n['name']} ({when})")
        lines.append("")

    return "\n".join(lines)


# --- Clock-time schedule + time-block formatting ----------------------------

import cd_paths
def _meal_params_path():
    # Resolved at call time so the test sandbox redirect (CD_DATA_DIR) takes effect.
    return cd_paths.data_file("meal_params.json")
_MEAL_PARAMS_DEFAULT = {
    "lunch": {
        "default_hour": 12.0,   # learned decimal hour (12.5 = 12:30); updated by corrections
        "window_end_hour": 15,  # past 3pm → skip (if she hasn't eaten by then, it's a different day)
        "duration_min": 30
    }
}

def _load_meal_params():
    try:
        with open(_meal_params_path()) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return _MEAL_PARAMS_DEFAULT


def update_meal_learned_time(meal_name, actual_hour, actual_minute=0):
    """Nudge the learned default time toward the actual time June had the meal.

    Called by the corrections loop (post-v1) when June moves a meal item in the plan.
    Uses a gentle exponential moving average (80% current, 20% new signal) so one
    outlier day doesn't override the pattern.
    """
    params = _load_meal_params()
    key = meal_name.lower()
    if key not in params:
        return
    actual_decimal = actual_hour + actual_minute / 60.0
    current = params[key]["default_hour"]
    params[key]["default_hour"] = round(0.8 * current + 0.2 * actual_decimal, 2)
    path = _meal_params_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(params, f, indent=2)


def default_meal_anchors(today_recurrings, start_time):
    """Return meal anchor items not already covered by a Recurring item.

    Timing is adaptive, not hardcoded:
    - If plan starts before the learned default lunch hour → anchor to that hour.
    - If plan starts after the default but before window_end → anchor to
      current_time + 30 min ("eat soon — you haven't had lunch yet").
    - If plan starts past window_end → skip (assume eaten or not happening today).

    The default_hour is a learned parameter updated by update_meal_learned_time()
    when the corrections loop (post-v1) sees June moving the Lunch item.
    June can also override entirely by adding a Recurring 'Lunch' item in Anytype.
    """
    existing = {r["name"].lower() for r in today_recurrings}
    params = _load_meal_params()
    anchors = []
    today = start_time.date()

    lp = params.get("lunch", _MEAL_PARAMS_DEFAULT["lunch"])
    window_end = dt.datetime.combine(today, dt.time(lp["window_end_hour"], 0))

    if start_time >= window_end:
        return []  # past the lunch window; don't nag

    if not any("lunch" in name for name in existing):
        default_h = lp["default_hour"]
        default_dt = dt.datetime.combine(
            today, dt.time(int(default_h), int((default_h % 1) * 60)))

        if start_time < default_dt:
            # Starting before learned lunch time — anchor to that time
            fixed = default_dt
        else:
            # Past the default but still in window — suggest lunch soon
            fixed = start_time + dt.timedelta(minutes=30)

        anchors.append({
            "id": None,
            "name": "Lunch",
            "fixed_time": fixed,
            "duration_min": lp["duration_min"],
            "_default_anchor": True,
        })

    return anchors


BREAK_WORK_MIN = 120      # a break after ~2h of focused work
BREAK_DURATION_MIN = 15   # a short (<20 min) break block

# Items that are themselves a break from focused/sitting work — they RESET the
# "time since last break" counter, so a break is never scheduled on top of lunch or
# a walk (June: "they don't need to account for things that are already breaks —
# walks, lunch, etc."). Detected by the meal-anchor flag, an existing break, or name.
_REST_KEYWORDS = ("lunch", "dinner", "breakfast", "meal", "walk", "nap", "rest",
                  "break", "stretch", "meditat", "relax", "coffee")


def _is_rest_item(item):
    if item.get("_break") or item.get("_default_anchor"):
        return True
    name = (item.get("name") or "").lower()
    return any(k in name for k in _REST_KEYWORDS)


def _compute_break_anchors(scheduled, start_time, end_time=None,
                           work_min_between=BREAK_WORK_MIN, break_min=BREAK_DURATION_MIN):
    """From a break-LESS scheduled timeline, return break blocks (fixed-time anchors)
    that punctuate extended stretches of actual work. A break only appears when there
    has been ~work_min_between minutes of real work AND more work follows. Rest items
    (meals, walks, naps — see _is_rest_item) reset the counter, and if a rest is
    already coming up next it serves as the break — so breaks never pile onto lunch or
    a walk. Breaks become real time-blocks when the schedule is rebuilt with them.
    """
    items = sorted(scheduled, key=lambda it: it["start_time"])
    anchors = []
    work_since_break = 0
    for idx, it in enumerate(items):
        if _is_rest_item(it):
            work_since_break = 0
            continue
        work_since_break += it.get("duration_min") or DEFAULT_DURATION_MIN
        if work_since_break < work_min_between:
            continue
        rest_of_day = items[idx + 1:]
        if not any(not _is_rest_item(x) for x in rest_of_day):
            continue                     # no real work left — don't end the day on a break
        if _is_rest_item(rest_of_day[0]):
            work_since_break = 0         # the next item is already a break — let it serve
            continue
        brk_time = it["end_time"]
        if end_time and brk_time >= end_time:
            break
        anchors.append({"name": "Break — stand, stretch, move",
                        "duration_min": break_min, "fixed_time": brk_time, "_break": True})
        work_since_break = 0
    return anchors


def build_schedule(llm_ordered_items, all_anchors, start_time=None, end_time=None):
    """Merge LLM-proposed task order with fixed anchors (Recurring + meal defaults).
    llm_ordered_items: list of {"name", "duration_min", ...} in proposed order.
    all_anchors: today_recurrings + default_meal_anchors (both have fixed_time).
    Returns scheduled list with start_time/end_time on each item.

    Past-fixed-time handling: if a recurring item's scheduled time has already passed,
    its time is GONE but the item is NOT assumed done — it floats to the current queue
    as a flexible item, labeled 'was HH:MM'. Past scheduled time ≠ done.
    """
    start_time = start_time or dt.datetime.now().replace(second=0, microsecond=0)
    existing_names = {it["name"] for it in llm_ordered_items}
    anchor_items = []
    for r in all_anchors:
        if r["name"] in existing_names:
            continue
        item = dict(r)
        ft = item.get("fixed_time")
        if ft is not None and ft < start_time:
            # Time passed — drop the anchor so it flows into the current queue.
            # Label it so the LLM and June know it was scheduled earlier.
            item["name"] = f"{item['name']} (was {_round_to_5(ft).strftime('%H:%M')})"
            del item["fixed_time"]
            item["_overdue"] = True
        anchor_items.append(item)
    base_items = list(llm_ordered_items) + anchor_items
    # First pass: schedule without breaks to see where lunch/walks actually land.
    scheduled = schedule(base_items, start_time, end_time=end_time)
    break_anchors = _compute_break_anchors(scheduled, start_time, end_time)
    if not break_anchors:
        return scheduled
    # Second pass: rebuild with the breaks placed as fixed-time anchors, so a break
    # only lands after a real stretch of work and never on top of an existing break.
    return schedule(base_items + break_anchors, start_time, end_time=end_time)


def _round_to_5(t):
    """Round a datetime to the nearest 5 minutes — cleaner to read, easier to hold mentally."""
    minutes = (t.minute + 2) // 5 * 5
    return t.replace(minute=0, second=0, microsecond=0) + dt.timedelta(minutes=minutes)


def _block_label(hour):
    if hour < 12:
        return "Morning"
    elif hour < 14:
        return "Midday"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"


def format_schedule_blocks(scheduled):
    """Group the Python-computed schedule into named time blocks.

    Claude reads this and adds narrative framing for each block, producing
    one integrated plan. Python owns times and order; Claude owns framing.
    """
    from collections import OrderedDict
    blocks: OrderedDict = OrderedDict()
    for item in scheduled:
        start = item.get("start_time")
        if not start:
            continue
        label = _block_label(start.hour)
        blocks.setdefault(label, []).append(item)

    def _fmt_time(t):
        return _round_to_5(t).strftime("%H:%M")

    lines = []
    lines.append("## Candidate moves — a SUGGESTED starting order (recompose freely)")
    lines.append("These are today's eligible next-moves in a calm default order. YOU compose the day:")
    lines.append("  1. Choose which of these belong in today (you need not include all — defer the")
    lines.append("     rest to still_here), ordered by the Focus Period intent + Strategies + capacity.")
    lines.append("  2. Write 1-2 sentence framing for each block (what it's for, energy note).")
    lines.append("  3. Produce ONE integrated plan. Put a placeholder time on each item — Python")
    lines.append("     computes the final clock times from YOUR order (you don't do the arithmetic).")
    lines.append("")

    for label, items in blocks.items():
        b_start = items[0]["start_time"]
        b_end = items[-1].get("end_time") or items[-1]["start_time"]
        lines.append(f"### {label} ({_fmt_time(b_start)} – {_fmt_time(b_end)})")
        for item in items:
            s = item.get("start_time")
            e = item.get("end_time")
            time_str = f"{_fmt_time(s)} – {_fmt_time(e)}" if s and e else "?"
            dur = item.get("duration_min")
            dur_str = f" (~{dur}min)" if dur else ""
            lines.append(f"  {time_str} | {item['name']}{dur_str}")
        lines.append("")

    return "\n".join(lines)


def blocks_from_scheduled(scheduled, framing_by_label=None):
    """Turn a Python-computed schedule (build_schedule output) into plan-dict blocks — the
    authoritative-times counterpart to format_schedule_blocks (which emits prompt TEXT). This is the
    'Python places it in time' step (AI_LAYER_SPEC:69) applied AFTER the LLM composes the order.

    Each scheduled item is either a COMPOSED item (a real task the LLM chose — carries `_composed`,
    plus task/project/why/id/held_back threaded by _resolve_ids) or an ANCHOR that build_schedule
    injected (meal, break, recurring). Composed items keep their display fields; anchors become plain
    rows (no id — matching the pre-existing behavior that meals/breaks/chores show no done-affordance).
    Emits the SAME `HH:MM – HH:MM` en-dash time-string contract format_schedule_blocks uses (three
    downstream consumers parse it by string ops)."""
    from collections import OrderedDict
    framing_by_label = framing_by_label or {}
    _chunked_today = chunk_log.chunked_today_ids()   # project_ids worked-on today (block checks)
    grouped: OrderedDict = OrderedDict()
    for item in scheduled:
        start = item.get("start_time")
        if not start:
            continue
        grouped.setdefault(_block_label(start.hour), []).append(item)

    def _fmt(t):
        return _round_to_5(t).strftime("%H:%M")

    blocks = []
    for label, items in grouped.items():
        b_start = items[0]["start_time"]
        b_end = items[-1].get("end_time") or items[-1]["start_time"]
        out_items = []
        for it in items:
            s, e = it.get("start_time"), it.get("end_time")
            time_str = f"{_fmt(s)} – {_fmt(e)}" if s and e else ""
            composed = bool(it.get("_composed"))
            row = {
                "time": time_str,
                "task": it.get("task") or it.get("name"),
                "project": it.get("project") if composed else None,
                "why": it.get("why") if composed else None,
                # a real composed task keeps its own (false) interstitial flag; an anchor is an
                # interstitial only when it's a Python-inserted break (meals/chores are not).
                "interstitial": bool(it.get("interstitial")) if composed else bool(it.get("_break")),
            }
            if composed:
                if it.get("id"):
                    row["id"] = it["id"]
                if it.get("held_back"):
                    row["held_back"] = it["held_back"]
                    row["held_back_names"] = it.get("held_back_names", [])
                if it.get("description"):
                    row["description"] = it["description"]
                if it.get("block"):
                    # A synthetic CONTAINER block (task-less project): a bare "work on X" chunk. The
                    # check is a daily "worked on it today" (chunk_log), NOT a task done — cache-only.
                    row["block"] = True
                    row["project_id"] = it.get("project_id")
                    row["shape"] = it.get("shape")
                    row["arc"] = it.get("arc")
                    row["chunk_min"] = it.get("chunk_min")
                    row["did_chunk_today"] = it.get("project_id") in _chunked_today
                elif it.get("block_project"):
                    # A REAL task whose project is block-work: keeps its own id/checkbox (row["id"]
                    # is the task — check-off marks it done). These fields let the overlay GROUP the
                    # project's rows under a "Work on X" header + its arc; the project-level
                    # did-a-chunk lives on that header (project_id), distinct from the task's done.
                    row["block_project"] = True
                    row["project_id"] = it.get("project_id")
                    row["arc"] = it.get("arc")
                    row["chunk_min"] = it.get("chunk_min")
                    row["did_chunk_today"] = it.get("project_id") in _chunked_today
            elif it.get("id") and not it.get("_break"):
                # A recurring chore/appointment anchor carries a real Anytype id. Expose it so the
                # overlay renders a checkbox, and flag it `recurring` so completion is a local
                # "done for today" (a cache flip — NOT an Anytype status write: Recurring objects
                # have no Task status, and they recur, so done-forever would be wrong). Meals and
                # Python-inserted breaks have no id / are breaks → stay un-checkable, as before.
                row["id"] = it["id"]
                row["recurring"] = True
            out_items.append(row)
        blocks.append({
            "label": label,
            "time": f"{_fmt(b_start)} – {_fmt(b_end)}",
            "framing": framing_by_label.get(label, ""),
            "items": out_items,
        })
    return blocks


PRIORITY_LIST_CAP = 6

def format_priority_list(ordered_items, period=None):
    """Fragmented-day output: a priority-ordered short list to pull from, no clock times.
    Python owns the order (foreground-first, from select_and_order_tasks); the model only
    adds plain framing. ADHD-friendly: few items, plain language, no clock pressure.
    (Addendum §"when the day has no fixed shape".)"""
    lines = ["## Today — a priority list to pull from (no fixed times)"]
    note = (period or {}).get("availability_note")
    if note:
        lines.append(f"_Availability: {note}_")
    lines.append("When you get some time, start at the top and take the next one that fits:")
    lines.append("")
    shown = ordered_items[:PRIORITY_LIST_CAP]
    for i, it in enumerate(shown, 1):
        dur = it.get("duration_min")
        lines.append(f"{i}. {it['name']}" + (f" (~{dur}min)" if dur else ""))
    remainder = len(ordered_items) - len(shown)
    if remainder > 0:
        lines.append(f"\n(+{remainder} more held for later — nothing to worry about today.)")
    return "\n".join(lines)


# --- "Fun / hobby" work → kept OUT of the daily plan (June, 2026-07-11) ------
# June thinks in three categories: Obligation / Wellbeing / Fun / hobby. Only "Fun / hobby"
# (self-directed creative/dev work) stays out of the daily plan, so it stops crowding out the
# rest. Obligation AND Wellbeing (walks, rest, care) both stay in. Reversible — flip
# INCLUDE_HOBBY_BLOCK back to True to bring the single open "your choice" block back. Necessary
# rest always stays in the plan regardless of side (see the _is_rest_item passthrough below).

OPEN_HOBBY_BLOCK_MIN = 60
HOBBY_BLOCK_DEFAULT = False  # default: fun/hobby out of the plan (June toggles it in overlay Settings)


def include_hobby_block():
    """Whether fun/hobby work appears in the plan as one open 'your choice' block. Persisted in
    settings.json, toggled live from the overlay Settings panel; HOBBY_BLOCK_DEFAULT if unset.
    (June, 2026-07-11: default OFF — hobby/creative/dev work stays out so it doesn't crowd out
    obligations. Necessary rest still shows regardless — see partition_by_side.)"""
    import cd_paths
    try:
        with open(cd_paths.config_file("settings.json")) as f:
            return bool(json.load(f).get("include_hobby_block", HOBBY_BLOCK_DEFAULT))
    except (FileNotFoundError, json.JSONDecodeError):
        return HOBBY_BLOCK_DEFAULT

def partition_by_side(tasks, projects):
    """Split tasks into (schedulable, hobby_excluded).

    Naming fix (June, 2026-07-13): this used to return (schedulable, wellbeing) — a leftover
    name from the old two-category (Obligation/Wellbeing) model, from before "Fun / hobby" was
    split out as its own third category. The logic was always correct (only Fun/hobby gets
    excluded; Wellbeing stays schedulable, per the docstring below) — only the variable name and
    surrounding comments still said "wellbeing" for what is actually the hobby-excluded bucket.

    A task is "fun / hobby" (self-directed creative / dev — the kind the system must NOT pick a
    thread *within*, per the never-pick-her-threads / linear-vs-nonlinear principle) iff at least
    one linked project has Side="Fun / hobby" AND none has Side in ("Obligation", "Wellbeing").
    Unlinked or unknown-side tasks stay schedulable — never hidden when unsure. **Necessary rest
    (walks, meals — _is_rest_item) always stays schedulable regardless of side**, so exercise/rest
    is never dropped as "hobby." Fun/hobby tasks are, by default, kept out (INCLUDE_HOBBY_BLOCK=False)."""
    side_by_name = {p["name"]: p.get("side") for p in projects}
    schedulable, hobby_excluded = [], []
    for t in tasks:
        if _is_rest_item(t):
            schedulable.append(t)  # necessary rest always stays, whatever it's linked to
            continue
        sides = [side_by_name.get(pn) for pn in (t.get("linked_projects") or [])]
        is_hobby = any(s == "Fun / hobby" for s in sides) and not any(s in ("Obligation", "Wellbeing") for s in sides)
        (hobby_excluded if is_hobby else schedulable).append(t)
    return schedulable, hobby_excluded


def open_hobby_block(hobby_tasks, duration_min=OPEN_HOBBY_BLOCK_MIN):
    """One open, self-directed block INSTEAD of system-picked hobby tasks: the system protects
    the time; June chooses the thread (from the Fun/hobby projects shown in context / the map).
    Returns a flexible schedule item, or None when there's no hobby work to protect time for."""
    if not hobby_tasks:
        return None
    return {"name": "Fun / hobby time — your choice of what to work on",
            "duration_min": duration_min, "fixed_time": None, "_open_block": True}


# --- Anytype writes ----------------------------------------------------------

def update_last_surfaced(sid, item_ids):
    """Write today's date to last_surfaced on each item."""
    today_iso = dt.date.today().isoformat()
    ls_prop = g.find_property("Last surfaced")
    if ls_prop is None:
        print("[warn] 'Last surfaced' property not found — skipping update", file=sys.stderr)
        return
    for oid in item_ids:
        call("PATCH", f"/spaces/{sid}/objects/{oid}",
             {"properties": [{"key": ls_prop["key"], "date": today_iso}]})


# --- Main -------------------------------------------------------------------

def run():
    import focus_period as fp
    import plan_generate
    sid = g.get_space_id()
    goals, projects, tasks, strategies, today_recurrings, period_ctx = load_active_items(sid)
    neglected = load_neglected()
    period = period_ctx["period"]
    is_off, in_window = period_ctx["is_off"], period_ctx["in_window"]

    print("\n=== Controlled Drift — Daily Plan ===\n")
    try:
        capacity = input("Capacity signal (one word/phrase, or Enter to skip): ").strip()
    except EOFError:
        capacity = ""

    # Python owns order + which shape; the LLM adds narrative framing around the skeleton.
    # Foreground drives selection; paused-project tasks are dropped.
    start_time = _round_to_5(dt.datetime.now())
    ordered = plan_generate.select_and_order_tasks(tasks, period)
    # Fun/hobby-side (self-directed creative/dev) work is kept out of the plan by default;
    # necessary rest stays regardless of side (see partition_by_side). Wellbeing-side work
    # (walks, care) is NOT excluded here — only Fun/hobby is.
    schedulable, hobby_excluded = partition_by_side(ordered, projects)
    # Engagement gate + one-move-per-thread — the SAME reduction the overlay path applies
    # (plan_generate.build_context). Without it, the chat "what should I do today" plan was built
    # from the WHOLE active pile — the overwhelm the 2026-07-11 selection fix removed on the overlay
    # but never reached this second, diverged pipeline. Now both paths gate identically.
    from surface_log import surfaced_dates
    schedulable = plan_generate._gate_and_collapse(schedulable, projects, neglected, period,
                                                   surface_dates=surfaced_dates())
    # NOTE (deliberate scope, 2026-07-13): rollover_ids is intentionally NOT passed here. Rollover
    # lives on the overlay/morning path (plan_generate.build_context), the only path that writes plan
    # snapshots. This chat path gets the overwhelm gate but not carry-over; wiring rollover through
    # here (incl. the "carried over" context block) is a deliberate follow-up, not a silent omission.
    hobby = open_hobby_block(hobby_excluded) if include_hobby_block() else None
    shape = fp.resolve_output_shape(period, in_window)
    scheduled = []
    if shape == "priority":
        # Fragmented day → a priority-list-to-pull-from, no clock times (the /drift chat-flow
        # output shape; the phone-overlay version lands in Phase 6).
        meals = []
        all_anchors = today_recurrings
        items = [{"name": t["name"], "duration_min": t.get("duration_min")} for t in schedulable]
        if hobby:
            items.append({"name": hobby["name"], "duration_min": hobby["duration_min"]})
        schedule_block = format_priority_list(items, period)
    else:
        meals = default_meal_anchors(today_recurrings, start_time)
        all_anchors = today_recurrings + meals
        task_items = [{"name": t["name"], "duration_min": t.get("duration_min")} for t in schedulable]
        if hobby:
            task_items.append({"name": hobby["name"], "duration_min": hobby["duration_min"]})
        scheduled = build_schedule(task_items, all_anchors, start_time)
        schedule_block = format_schedule_blocks(scheduled)

    context_block = format_context(
        goals, projects, tasks, strategies, today_recurrings, neglected, capacity,
        period=period, is_off=is_off, in_window=in_window)
    if period is None:
        context_block += ("\n\n## No active focus period\n"
                          "- No configuration for this stretch — if the plan feels off, June "
                          "may want to set one. Offer gently, once.")

    # Combine context + schedule skeleton so the LLM receives both
    full_context = context_block + "\n" + schedule_block

    # Read the prompt template
    prompt_path = os.path.join(os.path.dirname(__file__), "..", "prompts", "daily_list.md")
    with open(prompt_path) as f:
        prompt_template = f.read()

    # Inject context + schedule into prompt
    prompt = prompt_template.replace(
        "- Capacity signal: [what June said about today, or empty]",
        f"- Capacity signal: {capacity or '(none given)'}"
    ).replace(
        "- Active tasks/projects/goals/strategies: [via MCP]",
        f"- Active tasks/projects/goals/strategies:\n\n{full_context}"
    ).replace(
        "- Current time: [system time, for the downstream scheduler]",
        f"- Current time: {start_time.strftime('%A %B %d, %Y — %I:%M %p')}"
    )

    print("\n--- Context + schedule loaded. Prompt ready for LLM. ---")
    print(f"Goals: {len(goals)}  Projects: {len(projects)}  Tasks: {len(tasks)}  "
          f"Strategies: {len(strategies)}  Recurring today: {len(today_recurrings)}  "
          f"Meals injected: {len(meals)}  Neglected: {len(neglected)}")
    print("\nFull context (injected into daily_list.md prompt):\n")
    print(full_context)
    print("\n(In the /drift skill flow, the LLM receives this prompt and returns the")
    print(" integrated time-block plan with narrative framing. Run via /drift.)")

    try:
        confirm = input("\nConfirm and update last_surfaced? [y/N]: ").strip().lower()
    except EOFError:
        confirm = "n"
    if confirm == "y":
        # Only write to Anytype for real objects — exclude default meal anchors (no id)
        anytype_recurrings = [r for r in all_anchors if r.get("id")]
        surfaced_ids = [t["id"] for t in tasks] + [r["id"] for r in anytype_recurrings]
        update_last_surfaced(sid, surfaced_ids)
        log_surfaced_batch(
            [{"id": t["id"], "name": t["name"], "type": "task"} for t in tasks] +
            [{"id": r["id"], "name": r["name"], "type": "recurring"} for r in anytype_recurrings]
        )
        for item in scheduled:
            if item.get("start_time") and item.get("id"):
                log_correction("initial_placement", None,
                               {"name": item["name"],
                                "start": item["start_time"].isoformat(),
                                "end": item.get("end_time", "").isoformat() if item.get("end_time") else None})
        print(f"✓ Updated last_surfaced on {len(surfaced_ids)} items. Schedule logged.")


if __name__ == "__main__":
    run()
