#!/usr/bin/env python3
"""Daily plan pipeline — Step 2 of the Controlled Drift system.

Pipeline (§1 of daily_list.md):
  1. Load active items from Anytype (Goals, Projects, Tasks, Strategies, Recurring-for-today)
  2. Run neglect query (items not surfaced in N days)
  3. Ask June for a capacity signal
  4. Feed all context to the daily_list.md prompt → LLM proposes order + frame
  5. Compute clock-time schedule (deterministic Python, never LLM)
  6. Present the negotiable plan in chat
  7. On confirm: update last_surfaced in Anytype, append to surface_log, log corrections

Run: python3 scripts/daily_plan.py
     (or invoke via /drift when June asks "what should I do today")
"""
import sys, os, datetime as dt, json

sys.path.insert(0, os.path.dirname(__file__))
from anytype_test import call
import gsdo_anytype as g
from datetime_seam import recurring_items_for_today
from neglect import query_neglected
from scheduler import schedule, DEFAULT_DURATION_MIN
from surface_log import log_surfaced_batch
from plan_corrections_log import log_correction


# --- Data loading -----------------------------------------------------------

def _prop_val(props_dict, key, kind):
    p = props_dict.get(key, {})
    return p.get(kind) if p else None


def load_active_items(sid):
    """Load Goals, Projects, Tasks (Active/Needs-Clarifying), Strategies from Anytype."""
    data = g.fetch_all_objects(sid)
    goals, projects, tasks, strategies, recurrings = [], [], [], [], []
    # Project id -> name, for resolving a task's Linked Projects relation. That relation reads
    # back as a list of id STRINGS (not dicts), under the "objects" value — so it must be
    # resolved by id here, not read as dicts. (Fixes a long-standing empty-linked_projects bug.)
    proj_id_to_name = {o["id"]: o.get("name") for o in data
                       if isinstance(o.get("type"), dict) and o["type"].get("key") == "gsdo_project"}

    for obj in data:
        t = obj.get("type")
        tkey = t.get("key") if isinstance(t, dict) else t
        name = obj.get("name", "")
        oid = obj.get("id")
        props = {p.get("key"): p for p in obj.get("properties", [])}

        def pv(key, kind):
            return _prop_val(props, key, kind)

        if tkey == "gsdo_goal":
            status = (pv("gsdo_goal_status", "select") or {}).get("name")
            if status in (None, "Active"):
                props_by_name = {p.get("name"): p for p in obj.get("properties", [])}
                def pvn_g(nm, kind, _pbn=props_by_name):
                    p = _pbn.get(nm, {})
                    return p.get(kind) if p else None
                goals.append({"id": oid, "name": name,
                               "reaching_for": pv("gsdo_reaching_for_(text)", "text"),
                               "resolution_condition": pvn_g("Resolution condition", "text"),
                               "engagement": (pvn_g("Goal engagement", "select") or {}).get("name"),
                               "context": pv("gsdo_context", "text")})

        elif tkey == "gsdo_project":
            # Name-based lookup for the newer Engagement field (key generated by Anytype, not predictable).
            props_by_name = {p.get("name"): p for p in obj.get("properties", [])}
            def pvn(nm, kind, _pbn=props_by_name):
                p = _pbn.get(nm, {})
                return p.get(kind) if p else None

            engagement_tag = pvn("Engagement", "select") or {}
            engagement = engagement_tag.get("name") if isinstance(engagement_tag, dict) else None

            if engagement == "Done":
                continue  # Done projects are invisible in the daily plan

            # Obligation vs wellbeing — read by display name like Engagement (Anytype-generated key).
            side_tag = pvn("Side", "select") or {}
            side = side_tag.get("name") if isinstance(side_tag, dict) else None

            parent_proj_ids = pv("gsdo_parent_project", "objects") or []
            parent_project_id = parent_proj_ids[0] if parent_proj_ids else None

            projects.append({"id": oid, "name": name,
                              "reaching_for": pv("gsdo_reaching_for", "text"),
                              "context": pv("gsdo_context", "text"),
                              "affective": pv("gsdo_affective", "text"),
                              "deadline": pv("gsdo_deadline", "date"),
                              "engagement": engagement,
                              "engagement_notes": pvn("Engagement notes", "text"),
                              "side": side,
                              "parent_project_id": parent_project_id})

        elif tkey == "task":
            # The system's task status lives in the GSDO `gsdo_task_status` select (Active /
            # Ready / Done / Parked / …) — NOT the built-in `status`, which is vestigial and
            # always empty. Reading the built-in one silently included Done/Parked tasks in the
            # plan (they never got filtered). Read the property the rest of the system writes.
            status_tag = pv("gsdo_task_status", "select") or {}
            status = status_tag.get("name") if isinstance(status_tag, dict) else status_tag
            if status in (None, "Active", "Ready", "Needs Clarifying"):
                done = pv("done", "checkbox")
                if done:
                    continue
                # The tags live under the key `gsdo_access_conditions` (display "Access
                # conditions") — NOT `gsdo_access`. Reading the wrong key meant every task's
                # access tags came back empty since they were seeded (2026-07), so capacity/
                # access-aware planning had no signal to act on. (Fixed 2026-07-11.)
                access_tags = pv("gsdo_access_conditions", "multi_select") or []
                access = [t.get("name") for t in access_tags if isinstance(t, dict)]
                # The relation reads back under "objects" as a list of id strings (or dicts).
                # Resolve each to the current project name (rename-safe, by id).
                linked_raw = pv("linked_projects", "objects") or []
                linked_projects = []
                for x in linked_raw:
                    pid = x.get("id") if isinstance(x, dict) else x
                    nm = proj_id_to_name.get(pid)
                    if nm:
                        linked_projects.append(nm)
                tasks.append({"id": oid, "name": name,
                               "status": status,
                               "duration_min": pv("gsdo_duration_min", "number"),
                               "affective": pv("gsdo_affective", "text"),
                               "access": access,
                               "blocked_on": pv("gsdo_blocked_on", "text"),
                               "context": pv("gsdo_context", "text"),
                               "linked_projects": linked_projects})

        elif tkey == "gsdo_strategy":
            status = (pv("gsdo_status", "select") or {}).get("name")
            if status in (None, "Active"):
                strategies.append({"id": oid, "name": name,
                                    "what_for": pv("gsdo_what_for", "text"),
                                    "context": pv("gsdo_context", "text")})

        elif tkey == "gsdo_recurring":
            recurrings.append(obj)

    today_recurrings = recurring_items_for_today(recurrings)

    # Focus Period + resolved calendar facts — loaded HERE, the one seam both the terminal
    # (run) and live (plan_generate.build_context) paths call, so the feature reaches every
    # surface from one place, not just the terminal path. Reuses `data` — no second fetch.
    import focus_period as fp
    today = dt.date.today()
    period = fp.load_active_focus_period(data, today)
    if period:
        # Resolve foreground/paused project ids -> current names from the authoritative
        # projects list (rename-safe: the stored link is the id; the name is resolved live).
        # The relation reads back as id strings, so the name comes from here, not the stored value.
        id_to_name = {p["id"]: p["name"] for p in projects}
        def _resolve(pairs):
            return [id_to_name.get(i) or n for i, n in pairs if (i in id_to_name) or n]
        period["foreground"] = _resolve(period.get("foreground_pairs", []))
        period["paused"] = _resolve(period.get("paused_pairs", []))
    weekly_off = fp.load_day_off_defaults()
    period_ctx = {"period": period,
                  "is_off": fp.is_day_off(period, weekly_off, today),
                  "in_window": fp.in_availability_window(period, today)}
    return goals, projects, tasks, strategies, today_recurrings, period_ctx


def load_neglected(days=3):
    """Items not surfaced in N days (Tasks + Projects)."""
    try:
        return query_neglected(days=days)
    except Exception as e:
        print(f"[warn] neglect query failed: {e}", file=sys.stderr)
        return []


# --- Context formatting for the LLM ----------------------------------------

def format_context(goals, projects, tasks, strategies, today_recurrings, neglected, capacity,
                   period=None, is_off=False, in_window=False):
    """Build the context block that gets injected into the daily_list.md prompt."""
    lines = []

    lines.append(f"Current time: {dt.datetime.now().strftime('%A %B %d, %Y — %I:%M %p')}")
    lines.append(f"Capacity signal: {capacity or '(none given)'}")
    lines.append("")

    if period:
        lines.append("## This period — the configuration June authored")
        lines.append(f"- {period.get('name') or '(unnamed period)'}")
        if period.get("intent"):
            lines.append(f"- Intent: {period['intent']}")
        if is_off:
            lines.append("- Today is marked a DAY OFF — plan rest/protected time, not survival "
                         "work (unless June says otherwise or a hard deadline conflicts).")
        if in_window and period.get("availability_note"):
            lines.append(f"- Availability today: {period['availability_note']}")
        if period.get("foreground"):
            lines.append(f"- Foreground this period: {', '.join(period['foreground'])}")
        if period.get("paused"):
            lines.append(f"- Paused this period: {', '.join(period['paused'])}")
        if period.get("days_off_error"):
            lines.append("- A day-off setting couldn't be read — check it; today was planned "
                         "as a normal work day.")
        lines.append("")

    if strategies:
        lines.append("## Active strategies")
        for s in strategies:
            desc = s.get("what_for") or s.get("context") or ""
            lines.append(f"- {s['name']}" + (f": {desc}" if desc else ""))
        lines.append("")

    if goals:
        lines.append("## Active goals")
        lines.append("(engagement: Sprint → priority context; Steady → normal; Backburner → note but de-emphasize)")
        for g_ in goals:
            eng = g_.get("engagement") or "Steady"
            line = f"- {g_['name']} [{eng}]"
            rf = g_.get("reaching_for") or ""
            rc = g_.get("resolution_condition") or ""
            ctx = g_.get("context") or ""
            if rf:
                line += f" | reaching for: {rf}"
            if rc:
                line += f" | resolved when: {rc}"
            if ctx:
                line += f" | context: {ctx}"
            lines.append(line)
        lines.append("")

    if projects:
        lines.append("## Active projects")
        lines.append("(engagement: Sprint/Hyperfixation → priority real estate; Steady → daily move;"
                     " Backburner → only if neglected; Needs Clarifying → flag it)")
        lines.append("(sub-projects are indented under their parent)")

        fg = set((period or {}).get("foreground") or [])
        paused = set((period or {}).get("paused") or [])

        def _project_line(p, indent=""):
            eng = p.get("engagement") or "Steady"
            eng_notes = p.get("engagement_notes") or ""
            line = f"{indent}- {p['name']} [{eng}]"
            if p.get("side"):
                line += f" | side: {p['side']}"
            if p["name"] in paused:
                line += " [paused this period]"
            if eng_notes:
                line += f" | {eng_notes}"
            rf = p.get("reaching_for") or ""
            ctx = p.get("context") or ""
            aff = p.get("affective") or ""
            if rf:
                line += f" | reaching for: {rf}"
            if ctx:
                line += f" | context: {ctx}"
            if aff:
                line += f" | affective: {aff}"
            return line

        # Build tree: top-level projects first, then sub-projects nested under parent.
        # Foreground projects (period override) sort to the front — a display nicety; the
        # real reprioritization is in task selection (plan_generate.select_and_order_tasks).
        project_by_id = {p["id"]: p for p in projects}
        top_level = [p for p in projects if not p.get("parent_project_id")]
        top_level.sort(key=lambda p: (p["name"] not in fg, p["name"]))
        children_by_parent: dict = {}
        for p in projects:
            pid = p.get("parent_project_id")
            if pid:
                children_by_parent.setdefault(pid, []).append(p)

        for p in top_level:
            lines.append(_project_line(p))
            for child in children_by_parent.get(p["id"], []):
                lines.append(_project_line(child, indent="  "))
        # Orphaned sub-projects (parent not in active list) — show flat with note
        for p in projects:
            pid = p.get("parent_project_id")
            if pid and pid not in project_by_id:
                lines.append(_project_line(p) + " [sub-project]")
        lines.append("")

    if tasks:
        lines.append("## Active tasks by project/thread")
        lines.append("(The LLM should organize the plan by these project/thread groupings,")
        lines.append(" NOT by activity category like 'writing' or 'admin'.)")

        def _task_extras(t):
            extras = []
            if t.get("status") == "Needs Clarifying":
                extras.append("needs clarifying")
            if t.get("blocked_on"):
                extras.append(f"blocked on: {t['blocked_on']}")
            if t.get("duration_min"):
                extras.append(f"~{t['duration_min']}min")
            if t.get("affective"):
                extras.append(f"affective: {t['affective']}")
            if t.get("access"):
                extras.append(f"access: {', '.join(t['access'])}")
            return f" ({'; '.join(extras)})" if extras else ""

        # Group tasks by project. A task linked to multiple projects appears under each.
        project_tasks: dict = {}
        no_project = []
        for t in tasks:
            projs = t.get("linked_projects") or []
            if projs:
                for pn in projs:
                    project_tasks.setdefault(pn, []).append(t)
            else:
                no_project.append(t)

        for pname, ptasks in project_tasks.items():
            lines.append(f"- **{pname}**")
            for t in ptasks:
                lines.append(f"  - {t['name']}{_task_extras(t)}")
        if no_project:
            lines.append("- **[No project]**")
            for t in no_project:
                lines.append(f"  - {t['name']}{_task_extras(t)}")
        lines.append("")

    if today_recurrings:
        lines.append("## Recurring items scheduled today")
        for r in today_recurrings:
            lines.append(f"- {r['name']} at {r['fixed_time'].strftime('%H:%M')}")
        lines.append("")

    # Only show neglected items from ACTIVE projects (Steady/Sprint/Hyperfixation).
    # Backburner/Needs-Clarifying/unset projects going quiet is EXPECTED — don't surface that as a problem.
    # Also exclude: never-surfaced items (already in active lists), today's recurrings, already shown tasks.
    active_engagement = {"Steady", "Sprint", "Hyperfixation"}
    active_project_names = {p["name"] for p in projects
                            if p.get("engagement") in active_engagement or p.get("engagement") is None}
    active_names = {t["name"] for t in tasks} | {p["name"] for p in projects}
    neglected_stale = [n for n in neglected
                       if n.get("last_surfaced") is not None
                       and n["name"] not in {r["name"] for r in today_recurrings}
                       and n["name"] not in active_names
                       and any(pn in active_project_names
                               for pn in (n.get("linked_projects") or [active_project_names]))]
    if neglected_stale:
        lines.append("## Items from active projects that have gone quiet")
        lines.append("(These are in Steady/Sprint projects and haven't appeared in a plan recently.)")
        for n in neglected_stale:
            ls = n.get("last_surfaced")
            lines.append(f"- {n['name']} (last seen {ls.date()})")
        lines.append("")

    return "\n".join(lines)


# --- Clock-time schedule + time-block formatting ----------------------------

import cd_paths
def _meal_params_path():
    # Resolved at call time so the test sandbox redirect (CD_DATA_DIR) takes effect.
    return cd_paths.data_file("meal_params.json")
_MEAL_PARAMS_DEFAULT = {
    "lunch": {
        "default_hour": 12.0,   # learned decimal hour (12.5 = 12:30); updated by corrections
        "window_end_hour": 15,  # past 3pm → skip (if she hasn't eaten by then, it's a different day)
        "duration_min": 30
    }
}

def _load_meal_params():
    try:
        with open(_meal_params_path()) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return _MEAL_PARAMS_DEFAULT


def update_meal_learned_time(meal_name, actual_hour, actual_minute=0):
    """Nudge the learned default time toward the actual time June had the meal.

    Called by the corrections loop (post-v1) when June moves a meal item in the plan.
    Uses a gentle exponential moving average (80% current, 20% new signal) so one
    outlier day doesn't override the pattern.
    """
    params = _load_meal_params()
    key = meal_name.lower()
    if key not in params:
        return
    actual_decimal = actual_hour + actual_minute / 60.0
    current = params[key]["default_hour"]
    params[key]["default_hour"] = round(0.8 * current + 0.2 * actual_decimal, 2)
    path = _meal_params_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(params, f, indent=2)


def default_meal_anchors(today_recurrings, start_time):
    """Return meal anchor items not already covered by a Recurring item.

    Timing is adaptive, not hardcoded:
    - If plan starts before the learned default lunch hour → anchor to that hour.
    - If plan starts after the default but before window_end → anchor to
      current_time + 30 min ("eat soon — you haven't had lunch yet").
    - If plan starts past window_end → skip (assume eaten or not happening today).

    The default_hour is a learned parameter updated by update_meal_learned_time()
    when the corrections loop (post-v1) sees June moving the Lunch item.
    June can also override entirely by adding a Recurring 'Lunch' item in Anytype.
    """
    existing = {r["name"].lower() for r in today_recurrings}
    params = _load_meal_params()
    anchors = []
    today = start_time.date()

    lp = params.get("lunch", _MEAL_PARAMS_DEFAULT["lunch"])
    window_end = dt.datetime.combine(today, dt.time(lp["window_end_hour"], 0))

    if start_time >= window_end:
        return []  # past the lunch window; don't nag

    if not any("lunch" in name for name in existing):
        default_h = lp["default_hour"]
        default_dt = dt.datetime.combine(
            today, dt.time(int(default_h), int((default_h % 1) * 60)))

        if start_time < default_dt:
            # Starting before learned lunch time — anchor to that time
            fixed = default_dt
        else:
            # Past the default but still in window — suggest lunch soon
            fixed = start_time + dt.timedelta(minutes=30)

        anchors.append({
            "id": None,
            "name": "Lunch",
            "fixed_time": fixed,
            "duration_min": lp["duration_min"],
            "_default_anchor": True,
        })

    return anchors


BREAK_WORK_MIN = 120      # a break after ~2h of focused work
BREAK_DURATION_MIN = 15   # a short (<20 min) break block

# Items that are themselves a break from focused/sitting work — they RESET the
# "time since last break" counter, so a break is never scheduled on top of lunch or
# a walk (June: "they don't need to account for things that are already breaks —
# walks, lunch, etc."). Detected by the meal-anchor flag, an existing break, or name.
_REST_KEYWORDS = ("lunch", "dinner", "breakfast", "meal", "walk", "nap", "rest",
                  "break", "stretch", "meditat", "relax", "coffee")


def _is_rest_item(item):
    if item.get("_break") or item.get("_default_anchor"):
        return True
    name = (item.get("name") or "").lower()
    return any(k in name for k in _REST_KEYWORDS)


def _compute_break_anchors(scheduled, start_time, end_time=None,
                           work_min_between=BREAK_WORK_MIN, break_min=BREAK_DURATION_MIN):
    """From a break-LESS scheduled timeline, return break blocks (fixed-time anchors)
    that punctuate extended stretches of actual work. A break only appears when there
    has been ~work_min_between minutes of real work AND more work follows. Rest items
    (meals, walks, naps — see _is_rest_item) reset the counter, and if a rest is
    already coming up next it serves as the break — so breaks never pile onto lunch or
    a walk. Breaks become real time-blocks when the schedule is rebuilt with them.
    """
    items = sorted(scheduled, key=lambda it: it["start_time"])
    anchors = []
    work_since_break = 0
    for idx, it in enumerate(items):
        if _is_rest_item(it):
            work_since_break = 0
            continue
        work_since_break += it.get("duration_min") or DEFAULT_DURATION_MIN
        if work_since_break < work_min_between:
            continue
        rest_of_day = items[idx + 1:]
        if not any(not _is_rest_item(x) for x in rest_of_day):
            continue                     # no real work left — don't end the day on a break
        if _is_rest_item(rest_of_day[0]):
            work_since_break = 0         # the next item is already a break — let it serve
            continue
        brk_time = it["end_time"]
        if end_time and brk_time >= end_time:
            break
        anchors.append({"name": "Break — stand, stretch, move",
                        "duration_min": break_min, "fixed_time": brk_time, "_break": True})
        work_since_break = 0
    return anchors


def build_schedule(llm_ordered_items, all_anchors, start_time=None, end_time=None):
    """Merge LLM-proposed task order with fixed anchors (Recurring + meal defaults).
    llm_ordered_items: list of {"name", "duration_min", ...} in proposed order.
    all_anchors: today_recurrings + default_meal_anchors (both have fixed_time).
    Returns scheduled list with start_time/end_time on each item.

    Past-fixed-time handling: if a recurring item's scheduled time has already passed,
    its time is GONE but the item is NOT assumed done — it floats to the current queue
    as a flexible item, labeled 'was HH:MM'. Past scheduled time ≠ done.
    """
    start_time = start_time or dt.datetime.now().replace(second=0, microsecond=0)
    existing_names = {it["name"] for it in llm_ordered_items}
    anchor_items = []
    for r in all_anchors:
        if r["name"] in existing_names:
            continue
        item = dict(r)
        ft = item.get("fixed_time")
        if ft is not None and ft < start_time:
            # Time passed — drop the anchor so it flows into the current queue.
            # Label it so the LLM and June know it was scheduled earlier.
            item["name"] = f"{item['name']} (was {_round_to_5(ft).strftime('%H:%M')})"
            del item["fixed_time"]
            item["_overdue"] = True
        anchor_items.append(item)
    base_items = list(llm_ordered_items) + anchor_items
    # First pass: schedule without breaks to see where lunch/walks actually land.
    scheduled = schedule(base_items, start_time, end_time=end_time)
    break_anchors = _compute_break_anchors(scheduled, start_time, end_time)
    if not break_anchors:
        return scheduled
    # Second pass: rebuild with the breaks placed as fixed-time anchors, so a break
    # only lands after a real stretch of work and never on top of an existing break.
    return schedule(base_items + break_anchors, start_time, end_time=end_time)


def _round_to_5(t):
    """Round a datetime to the nearest 5 minutes — cleaner to read, easier to hold mentally."""
    minutes = (t.minute + 2) // 5 * 5
    return t.replace(minute=0, second=0, microsecond=0) + dt.timedelta(minutes=minutes)


def _block_label(hour):
    if hour < 12:
        return "Morning"
    elif hour < 14:
        return "Midday"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"


def format_schedule_blocks(scheduled):
    """Group the Python-computed schedule into named time blocks.

    Claude reads this and adds narrative framing for each block, producing
    one integrated plan. Python owns times and order; Claude owns framing.
    """
    from collections import OrderedDict
    blocks: OrderedDict = OrderedDict()
    for item in scheduled:
        start = item.get("start_time")
        if not start:
            continue
        label = _block_label(start.hour)
        blocks.setdefault(label, []).append(item)

    def _fmt_time(t):
        return _round_to_5(t).strftime("%H:%M")

    lines = []
    lines.append("## Pre-computed clock schedule — your output skeleton")
    lines.append("Python owns times and order. Your job:")
    lines.append("  1. Write 1-2 sentence narrative framing for each block (what it's for, energy note).")
    lines.append("  2. List each item with its clock time verbatim.")
    lines.append("  3. Produce ONE integrated plan — not a narrative followed by a separate schedule.")
    lines.append("  Do not change times or reorder items.")
    lines.append("")

    for label, items in blocks.items():
        b_start = items[0]["start_time"]
        b_end = items[-1].get("end_time") or items[-1]["start_time"]
        lines.append(f"### {label} ({_fmt_time(b_start)} – {_fmt_time(b_end)})")
        for item in items:
            s = item.get("start_time")
            e = item.get("end_time")
            time_str = f"{_fmt_time(s)} – {_fmt_time(e)}" if s and e else "?"
            dur = item.get("duration_min")
            dur_str = f" (~{dur}min)" if dur else ""
            lines.append(f"  {time_str} | {item['name']}{dur_str}")
        lines.append("")

    return "\n".join(lines)


PRIORITY_LIST_CAP = 6

def format_priority_list(ordered_items, period=None):
    """Fragmented-day output: a priority-ordered short list to pull from, no clock times.
    Python owns the order (foreground-first, from select_and_order_tasks); the model only
    adds plain framing. ADHD-friendly: few items, plain language, no clock pressure.
    (Addendum §"when the day has no fixed shape".)"""
    lines = ["## Today — a priority list to pull from (no fixed times)"]
    note = (period or {}).get("availability_note")
    if note:
        lines.append(f"_Availability: {note}_")
    lines.append("When you get some time, start at the top and take the next one that fits:")
    lines.append("")
    shown = ordered_items[:PRIORITY_LIST_CAP]
    for i, it in enumerate(shown, 1):
        dur = it.get("duration_min")
        lines.append(f"{i}. {it['name']}" + (f" (~{dur}min)" if dur else ""))
    remainder = len(ordered_items) - len(shown)
    if remainder > 0:
        lines.append(f"\n(+{remainder} more held for later — nothing to worry about today.)")
    return "\n".join(lines)


# --- Wellbeing-side work → kept OUT of the daily plan (June, 2026-07-11) ------
# June's decision: fun/hobby/creative/dev work stays out of the daily plan entirely, so it
# stops crowding out obligations. Reversible — flip INCLUDE_HOBBY_BLOCK back to True to bring
# the single open "your choice" block back. Necessary rest (walks, meals) always stays in the
# plan regardless of side (see the _is_rest_item passthrough in partition_by_side).

OPEN_HOBBY_BLOCK_MIN = 60
HOBBY_BLOCK_DEFAULT = False  # default: fun/hobby out of the plan (June toggles it in overlay Settings)


def include_hobby_block():
    """Whether fun/hobby work appears in the plan as one open 'your choice' block. Persisted in
    settings.json, toggled live from the overlay Settings panel; HOBBY_BLOCK_DEFAULT if unset.
    (June, 2026-07-11: default OFF — hobby/creative/dev work stays out so it doesn't crowd out
    obligations. Necessary rest still shows regardless — see partition_by_side.)"""
    import cd_paths
    try:
        with open(cd_paths.config_file("settings.json")) as f:
            return bool(json.load(f).get("include_hobby_block", HOBBY_BLOCK_DEFAULT))
    except (FileNotFoundError, json.JSONDecodeError):
        return HOBBY_BLOCK_DEFAULT

def partition_by_side(tasks, projects):
    """Split tasks into (schedulable, wellbeing).

    A task is WELLBEING (hobby / creative / dev — the kind the system must NOT pick a thread
    *within*, per the never-pick-her-threads / linear-vs-nonlinear principle) iff at least one
    linked project is Wellbeing-side AND none is Obligation-side. Unlinked or unknown-side tasks
    stay schedulable — never hidden when unsure. **Necessary rest (walks, meals — _is_rest_item)
    always stays schedulable regardless of side**, so exercise/rest is never dropped as "hobby."
    Wellbeing tasks are, by default, kept out of the plan entirely (INCLUDE_HOBBY_BLOCK=False)."""
    side_by_name = {p["name"]: p.get("side") for p in projects}
    schedulable, wellbeing = [], []
    for t in tasks:
        if _is_rest_item(t):
            schedulable.append(t)  # necessary rest always stays, whatever it's linked to
            continue
        sides = [side_by_name.get(pn) for pn in (t.get("linked_projects") or [])]
        is_well = any(s == "Wellbeing" for s in sides) and not any(s == "Obligation" for s in sides)
        (wellbeing if is_well else schedulable).append(t)
    return schedulable, wellbeing


def open_hobby_block(wellbeing_tasks, duration_min=OPEN_HOBBY_BLOCK_MIN):
    """One open, self-directed block INSTEAD of system-picked hobby tasks: the system protects
    the time; June chooses the thread (from the Wellbeing projects shown in context / the map).
    Returns a flexible schedule item, or None when there's no wellbeing work to protect time for."""
    if not wellbeing_tasks:
        return None
    return {"name": "Fun / hobby time — your choice of what to work on",
            "duration_min": duration_min, "fixed_time": None, "_open_block": True}


# --- Anytype writes ----------------------------------------------------------

def update_last_surfaced(sid, item_ids):
    """Write today's date to last_surfaced on each item."""
    today_iso = dt.date.today().isoformat()
    ls_prop = g.find_property("Last surfaced")
    if ls_prop is None:
        print("[warn] 'Last surfaced' property not found — skipping update", file=sys.stderr)
        return
    for oid in item_ids:
        call("PATCH", f"/spaces/{sid}/objects/{oid}",
             {"properties": [{"key": ls_prop["key"], "date": today_iso}]})


# --- Main -------------------------------------------------------------------

def run():
    import focus_period as fp
    import plan_generate
    sid = g.get_space_id()
    goals, projects, tasks, strategies, today_recurrings, period_ctx = load_active_items(sid)
    neglected = load_neglected()
    period = period_ctx["period"]
    is_off, in_window = period_ctx["is_off"], period_ctx["in_window"]

    print("\n=== Controlled Drift — Daily Plan ===\n")
    try:
        capacity = input("Capacity signal (one word/phrase, or Enter to skip): ").strip()
    except EOFError:
        capacity = ""

    # Python owns order + which shape; the LLM adds narrative framing around the skeleton.
    # Foreground drives selection; paused-project tasks are dropped.
    start_time = _round_to_5(dt.datetime.now())
    ordered = plan_generate.select_and_order_tasks(tasks, period)
    # Wellbeing-side (hobby/creative/dev) work is kept out of the plan by default; rest stays.
    schedulable, wellbeing = partition_by_side(ordered, projects)
    hobby = open_hobby_block(wellbeing) if include_hobby_block() else None
    shape = fp.resolve_output_shape(period, in_window)
    scheduled = []
    if shape == "priority":
        # Fragmented day → a priority-list-to-pull-from, no clock times (the /drift chat-flow
        # output shape; the phone-overlay version lands in Phase 6).
        meals = []
        all_anchors = today_recurrings
        items = [{"name": t["name"], "duration_min": t.get("duration_min")} for t in schedulable]
        if hobby:
            items.append({"name": hobby["name"], "duration_min": hobby["duration_min"]})
        schedule_block = format_priority_list(items, period)
    else:
        meals = default_meal_anchors(today_recurrings, start_time)
        all_anchors = today_recurrings + meals
        task_items = [{"name": t["name"], "duration_min": t.get("duration_min")} for t in schedulable]
        if hobby:
            task_items.append({"name": hobby["name"], "duration_min": hobby["duration_min"]})
        scheduled = build_schedule(task_items, all_anchors, start_time)
        schedule_block = format_schedule_blocks(scheduled)

    context_block = format_context(
        goals, projects, tasks, strategies, today_recurrings, neglected, capacity,
        period=period, is_off=is_off, in_window=in_window)
    if period is None:
        context_block += ("\n\n## No active focus period\n"
                          "- No configuration for this stretch — if the plan feels off, June "
                          "may want to set one. Offer gently, once.")

    # Combine context + schedule skeleton so the LLM receives both
    full_context = context_block + "\n" + schedule_block

    # Read the prompt template
    prompt_path = os.path.join(os.path.dirname(__file__), "..", "prompts", "daily_list.md")
    with open(prompt_path) as f:
        prompt_template = f.read()

    # Inject context + schedule into prompt
    prompt = prompt_template.replace(
        "- Capacity signal: [what June said about today, or empty]",
        f"- Capacity signal: {capacity or '(none given)'}"
    ).replace(
        "- Active tasks/projects/goals/strategies: [via MCP]",
        f"- Active tasks/projects/goals/strategies:\n\n{full_context}"
    ).replace(
        "- Current time: [system time, for the downstream scheduler]",
        f"- Current time: {start_time.strftime('%A %B %d, %Y — %I:%M %p')}"
    )

    print("\n--- Context + schedule loaded. Prompt ready for LLM. ---")
    print(f"Goals: {len(goals)}  Projects: {len(projects)}  Tasks: {len(tasks)}  "
          f"Strategies: {len(strategies)}  Recurring today: {len(today_recurrings)}  "
          f"Meals injected: {len(meals)}  Neglected: {len(neglected)}")
    print("\nFull context (injected into daily_list.md prompt):\n")
    print(full_context)
    print("\n(In the /drift skill flow, the LLM receives this prompt and returns the")
    print(" integrated time-block plan with narrative framing. Run via /drift.)")

    try:
        confirm = input("\nConfirm and update last_surfaced? [y/N]: ").strip().lower()
    except EOFError:
        confirm = "n"
    if confirm == "y":
        # Only write to Anytype for real objects — exclude default meal anchors (no id)
        anytype_recurrings = [r for r in all_anchors if r.get("id")]
        surfaced_ids = [t["id"] for t in tasks] + [r["id"] for r in anytype_recurrings]
        update_last_surfaced(sid, surfaced_ids)
        log_surfaced_batch(
            [{"id": t["id"], "name": t["name"], "type": "task"} for t in tasks] +
            [{"id": r["id"], "name": r["name"], "type": "recurring"} for r in anytype_recurrings]
        )
        for item in scheduled:
            if item.get("start_time") and item.get("id"):
                log_correction("initial_placement", None,
                               {"name": item["name"],
                                "start": item["start_time"].isoformat(),
                                "end": item.get("end_time", "").isoformat() if item.get("end_time") else None})
        print(f"✓ Updated last_surfaced on {len(surfaced_ids)} items. Schedule logged.")


if __name__ == "__main__":
    run()
