/**
 * Controlled Drift — design tokens
 * Generated by reconciliation on 2026-07-17.
 *
 * CANONICAL SOURCE: design/mockups/color-system.html (the rendered gallery).
 * That page is what the owner tuned against; where it disagrees with the
 * buildThemes() object in design/mockups/review-reorganize-mobile-v4.html,
 * THE GALLERY WINS and the value here is the gallery's.
 *
 * Structure (key names, nesting) is inherited from v4 buildThemes() so the
 * mapping back to the mockup stays auditable. Every corrected line carries a
 * trailing comment naming the old v4 value.
 *
 * Values were mined ONLY from gallery sections 4a (celestial phone, ~L31-80),
 * 4c (hardware phone, ~L81-138), 5a (celestial component kit, ~L139-220) and
 * 5c (hardware component kit, ~L221-296). Sections 1a/1b, 2a/2b and 3a/3b/3c
 * are superseded explorations (the page itself notes at ~L605 that the palette
 * "grew into ~10 competing bright hues" before being cut back) and were NOT
 * used as sources.
 *
 * Unresolved questions are NOT silently decided here — see RECONCILIATION.md
 * "Ambiguities". Tokens still carrying an unverified v4 value are marked
 * `// UNVERIFIED`.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export type ThemeName = 'celestial' | 'hardware';

export interface ThemeColors {
  bg: string;
  panel: string;
  panel2: string;
  surface: string;
  surface2: string;
  border: string;
  hair: string;
  rose: string;
  roseBg: string;
  roseBorder: string;
  roseDim: string;
  gold: string;
  goldDim: string;
  text: string;
  dim: string;
  dimmer: string;
  blue: string;
  green: string;
  amber: string;
  teal: string;
  purple: string;
  orange: string;
  red: string;
  strategy: string;
  horizon: string;
  side: string;
  sig: string;
  on: string;
  onGreen: string;
  box: string;
  inkBg: string;
  inkBorder: string;
  actBg: string;
  actBorder: string;
  /** NEW — gallery neutral between `text` and `dim` (list-row labels, menu items). */
  textSoft: string;
  /** NEW — gallery neutral between `dim` and `dimmer` (ghost buttons, inactive tabs/segments). */
  dim2: string;
  /** NEW — dimmest readable neutral (placeholders, "off" numerals, meta labels). */
  dimmest: string;
  /**
   * NEW — the stroke on an UNSET chip (gallery L153, the "Parked" chip) and the unchecked `☐`
   * text glyph (L60).
   *
   * ⚠ CORRECTED 2026-07-18. This previously read "empty checkbox, unchecked glyph, dead status
   * dot" — an extrapolation not supported by RECONCILIATION.md, which sources this token only
   * from L60 and L153. A component author trusted the wrong docstring and applied it to the
   * checkbox, rendering the most-repeated control in the app visibly fainter than the gallery.
   * The empty CHECKBOX stroke is `dimmer` (celestial `#6f6480`, gallery 5a) / `dimmest`
   * (hardware `#5f6a86`, gallery 5c). Do not use `disabled` for checkboxes.
   */
  disabled: string;
}

export interface ThemeRadii {
  chip: string;
  card: string;
  field: string;
  ctl: string;
  mod: string;
}

/** Effects that were inline literals in v4's render code, now named. */
export interface ThemeEffects {
  /** Top inner-bevel highlight on raised surfaces. */
  bevelHighlight: string;
  /** Stronger bevel highlight, primary/emphasised controls. */
  bevelHighlightStrong: string;
  /** Bottom inner-bevel shadow on raised surfaces. */
  bevelShadow: string;
  /** Inset well shadow for recessed fields / sunken tracks. */
  bevelInset: string;
  /** Deeper inset well (toggle-off track). */
  bevelInsetDeep: string;
  /** Hairline top highlight on the outermost container. */
  containerHighlight: string;
  /** Drop shadow of the outermost container/card stack. */
  containerShadow: string;
  /** Drop shadow of floating panes (menus, popovers). */
  paneShadow: string;
  /** Glass fill used for translucent chrome over the background. */
  glassFill: string;
  /** Faint glass fill (inactive controls). */
  glassFillFaint: string;
  /** Glass hairline border. */
  glassBorder: string;
  /** Top-accent bar under the app chrome. */
  topAccent: string;
  /** Height of the top-accent bar. */
  topAccentHeight: string;
  /** Glow beneath the top-accent bar. */
  topAccentGlow: string;
  /** Background texture recipe (starfield / instrument grid). */
  star: string;
  /** Ambient nebula/bloom washes layered under content. */
  ambient: string;
  /** Small emphasis glow: `glowSm(color)` -> box-shadow. */
  glowSm: (c: string) => string;
  /** Large two-stop status-dot glow: `glowLg(color)` -> box-shadow. */
  glowLg: (c: string) => string;
  /** Focus/selection ring for a checkbox or completion control. */
  glowRing: (c: string) => string;
  /** Text glow for lit glyphs (✓ / [x] / ✦ markers). */
  glowText: (c: string) => string;
  /** Solid-fill feedback pill glow (toasts). */
  glowToast: (c: string) => string;
  /** Primary-button ambient glow. */
  glowButton: (c: string) => string;
}

export interface Theme {
  name: ThemeName;
  mode: ThemeName;
  label: string;
  tag: string;
  chip: 'soft' | 'hard';
  font: string;
  mono: string;
  r: ThemeRadii;
  chrome: string;
  blur: string;
  pane: string;
  paneBlur: string;
  star: string;
  c: ThemeColors;
  effects: ThemeEffects;
}

// ─── Shared derivations ──────────────────────────────────────────────────────

/**
 * Chip fill / border alphas, taken from the gallery's explicit rgba() values
 * rather than v4's hex-suffix concatenation.
 *
 * Gallery celestial (L146-149): `background:rgba(R,G,B,.14); border:1px solid rgba(R,G,B,.4)`
 * Gallery hardware  (L228-231): `background:linear-gradient(180deg,rgba(R,G,B,.14),rgba(R,G,B,.05)); border:1px solid rgba(R,G,B,.4)`
 *
 * v4 expressed the same thing as `c.color+'24'` / `c.color+'0d'` / `c.color+'66'`
 * (= 0.141 / 0.051 / 0.400). The gallery's round numbers are authoritative.
 */
export const chipFillAlpha = 0.14;
export const chipFillAlphaBottom = 0.05; // hardware gradient foot only
export const chipBorderAlpha = 0.4;

/** Fill alpha for a *selected* segmented/toggle control (not a chip). */
export const selectedFillAlpha = { celestial: 0.16, hardware: 0.18 } as const;

/** #rrggbb -> "r,g,b". Throws on malformed input rather than failing silently. */
export function rgbTriplet(hex: string): string {
  const m = /^#([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`rgbTriplet: expected #rrggbb, got ${hex}`);
  const n = parseInt(m[1]!, 16);
  return `${(n >> 16) & 255},${(n >> 8) & 255},${n & 255}`;
}

/** Compose a translucent colour the way the gallery writes them. */
export function alpha(hex: string, a: number): string {
  return `rgba(${rgbTriplet(hex)},${a})`;
}

/** Chip surface for an accent colour, per theme. Replaces v4's `C.sig+'22'` style. */
export function chipFill(hex: string, mode: ThemeName): string {
  return mode === 'hardware'
    ? `linear-gradient(180deg,${alpha(hex, chipFillAlpha)},${alpha(hex, chipFillAlphaBottom)})`
    : alpha(hex, chipFillAlpha);
}

/** Chip border for an accent colour. */
export function chipBorder(hex: string): string {
  return `1px solid ${alpha(hex, chipBorderAlpha)}`;
}

const MONO = "'JetBrains Mono',ui-monospace,SFMono-Regular,Menlo,monospace";

// ─── Celestial ───────────────────────────────────────────────────────────────

const cel: ThemeColors = {
  bg: '#060512',                            // was #0a0812 in v4 buildThemes — gallery L34 (4a phone base)
  panel: 'rgba(255,255,255,0.04)',          // was rgba(255,255,255,0.045) — gallery L40,L71-73,L180-181
  panel2: 'rgba(255,255,255,0.09)',
  surface: 'rgba(255,255,255,0.05)',        // gallery L171,L193
  surface2: 'rgba(255,255,255,0.1)',        // gallery L171,L180
  border: 'rgba(255,255,255,0.09)',         // was rgba(255,255,255,0.11) — gallery L40,L71-73,L181,L195
  hair: 'rgba(255,255,255,0.06)',           // gallery L43,L57,L62,L69
  rose: '#f2a6c8',                          // gallery L44,L55,L70,L170,L182
  roseBg: 'rgba(239,146,189,0.07)',         // was rgba(239,146,189,0.08) — gallery L55
  roseBorder: 'rgba(239,146,189,0.24)',     // was rgba(239,146,189,0.26) — gallery L55
  roseDim: '#b07f96',                       // was #b98aa0 — gallery L55 ("why this matters" eyebrow)
  gold: '#f0a86a',                          // was #f0b46a — gallery never renders #f0b46a in 4a/5a; see RECONCILIATION §Ambiguities
  goldDim: 'rgba(240,168,106,0.22)',        // was rgba(240,180,106,0.22) — hue corrected to #f0a86a; alpha UNVERIFIED
  text: '#f5eef2',                          // gallery L32,L36,L39,L54,L64,L141,L193
  dim: '#a89aa6',                           // gallery L40,L53,L59,L71-73,L171,L179,L192
  dimmer: '#6f6480',                        // gallery L64,L66,L75,L144,L153,L180,L198
  blue: '#7fb2f5',                          // UNVERIFIED — no celestial 4a/5a occurrence; see RECONCILIATION §Ambiguities
  green: '#58d69a',                         // gallery L60,L64,L146,L186,L211
  amber: '#f0a86a',                         // was #f0b46a — same correction as `gold`
  teal: '#5fc6d6',                          // gallery L53,L140,L161
  purple: '#a98fee',                        // gallery L59
  orange: '#f0a86a',                        // gallery L59,L148,L152,L194
  red: '#ef7683',                           // gallery L173,L206
  strategy: '#d58fd8',                      // gallery L140,L164
  horizon: '#9fb4cf',                       // UNVERIFIED — no gallery occurrence
  side: '#9aa0e0',                          // gallery L149
  sig: '#ef92bd',                           // gallery L32,L44,L140,L141,L147,L212
  on: '#14101a',                            // was #150c18 — gallery L154 (solid accent chip label)
  onGreen: '#062018',                       // gallery L186,L211
  box: 'rgba(0,0,0,0.28)',                  // UNVERIFIED — celestial has no matching flat well
  inkBg: 'rgba(255,255,255,0.03)',          // was rgba(0,0,0,0.32) — gallery L75,L198 (celestial input is a white veil, not an ink well)
  inkBorder: 'rgba(255,255,255,0.08)',      // was rgba(255,255,255,0.09) — gallery L75,L198
  actBg: 'rgba(240,168,106,0.14)',          // was rgba(240,180,106,0.13) — gallery L148,L194
  actBorder: 'rgba(240,168,106,0.4)',       // was rgba(240,180,106,0.4) — hue corrected; gallery L148,L194
  textSoft: '#d7d0da',                      // NEW — gallery L160-164,L205
  dim2: '#8a8090',                          // NEW — gallery L32,L39,L45-48,L60,L172,L183-184,L195
  dimmest: '#6f6480',                       // NEW — celestial does not split placeholder from `dimmer`; gallery L75,L198
  disabled: '#4f4a5e',                      // NEW — gallery L60,L153
};

const celStar =
  'radial-gradient(1.5px 1.5px at 14% 10%,rgba(255,255,255,.5),transparent 60%),' +
  'radial-gradient(1px 1px at 66% 6%,rgba(255,255,255,.4),transparent 60%),' +
  'radial-gradient(1px 1px at 88% 22%,rgba(255,255,255,.45),transparent 60%),' +
  'radial-gradient(1px 1px at 34% 30%,rgba(255,214,232,.34),transparent 60%),' +
  'radial-gradient(1px 1px at 52% 44%,rgba(215,232,255,.3),transparent 60%),' +
  'radial-gradient(1.3px 1.3px at 78% 52%,rgba(255,255,255,.4),transparent 60%),' +
  'radial-gradient(1px 1px at 20% 62%,rgba(255,240,214,.3),transparent 60%),' +
  'radial-gradient(1px 1px at 62% 74%,rgba(255,255,255,.34),transparent 60%),' +
  'radial-gradient(1px 1px at 40% 86%,rgba(255,255,255,.3),transparent 60%)';

const celAmbient =
  'radial-gradient(120% 60% at 82% 0%,rgba(224,96,168,.22),transparent 55%),' +
  'radial-gradient(120% 70% at 5% 100%,rgba(48,150,190,.18),transparent 55%),' +
  'radial-gradient(90% 50% at 50% 42%,rgba(150,90,205,.1),transparent 70%)';

const celEffects: ThemeEffects = {
  bevelHighlight: 'inset 0 1px 0 rgba(255,255,255,0.05)',          // gallery L139
  bevelHighlightStrong: 'inset 0 1px 0 rgba(255,255,255,0.12)',    // v4 glow() literal; celestial has no gallery bevel
  bevelShadow: 'inset 0 -1px 0 rgba(0,0,0,0.32)',                  // hardware-derived; celestial does not bevel
  bevelInset: 'inset 0 0 4px rgba(0,0,0,0.5)',                     // gallery L180 (toggle-off knob)
  bevelInsetDeep: 'inset 0 1px 3px rgba(0,0,0,0.5)',
  containerHighlight: 'inset 0 1px 0 rgba(255,255,255,0.05)',      // gallery L139
  containerShadow: '0 34px 90px rgba(0,0,0,0.6)',                  // gallery L139
  paneShadow: '0 16px 34px rgba(0,0,0,0.5)',                       // gallery L203
  glassFill: 'rgba(255,255,255,0.05)',                             // gallery L171
  glassFillFaint: 'rgba(255,255,255,0.03)',                        // gallery L75,L198
  glassBorder: '1px solid rgba(255,255,255,0.06)',                 // gallery L139
  topAccent: 'linear-gradient(90deg,#ef92bd,#d58fd8,#5fc6d6)',     // gallery L140 — v4 started from C.rose (#f2a6c8), gallery starts from sig (#ef92bd)
  topAccentHeight: '2px',                                          // gallery L140
  // ⚠ CORRECTED 2026-07-18 → 'none'. Was '0 8px 14px -8px rgba(239,146,189,0.8)', mined from
  // gallery L44 — which is the ACTIVE-TAB UNDERLINE, a different element. The trusted top-accent
  // bar (5a L140) is `height:2px;background:linear-gradient(...)` with no shadow at all. The old
  // value put a pink bloom under the bar that the gallery does not have.
  topAccentGlow: 'none',                                           // gallery L140 carries no glow
  star: celStar,                                                   // gallery L139 — 9-star recipe; see RECONCILIATION §Ambiguities
  ambient: celAmbient,                                             // gallery L34
  glowSm: (c) => `0 0 7px ${alpha(c, 0.6)}`,                        // gallery L160-164
  glowLg: (c) => `0 0 4px ${alpha(c, 0.85)},0 0 11px 2px ${alpha(c, 0.45)}`, // gallery L53,L59
  glowRing: (c) => `0 0 3px ${alpha(c, 0.6)},0 0 9px 1px ${alpha(c, 0.4)},inset 0 0 4px ${alpha(c, 0.3)}`, // gallery L64
  glowText: (c) => `0 0 3px ${alpha(c, 0.9)},0 0 9px ${alpha(c, 0.65)}`,     // gallery L60
  glowToast: (c) => `0 0 18px ${alpha(c, 0.5)}`,                    // gallery L211
  glowButton: (c) => `0 0 16px ${alpha(c, 0.24)}`,                  // gallery L170
};

// ─── Hardware ────────────────────────────────────────────────────────────────

const hw: ThemeColors = {
  bg: '#07080f',                            // gallery L84,L221
  panel: 'rgba(18,22,34,0.66)',             // was rgba(20,24,38,0.62) — gallery L102,L107 (top stop of the card gradient; see effects.panelGradient note in RECONCILIATION)
  panel2: 'rgba(255,255,255,0.06)',
  surface: 'rgba(255,255,255,0.03)',        // was rgba(16,20,32,0.72) — gallery L95-97,L277-278
  surface2: 'rgba(255,255,255,0.08)',
  border: 'rgba(255,255,255,0.1)',          // gallery L119,L263,L277,L280
  hair: 'rgba(255,255,255,0.06)',           // was rgba(255,255,255,0.07) — gallery L223
  rose: '#f593c1',                          // was #f6aecd — gallery L105,L115,L222,L229,L252,L286,L294
  roseBg: 'rgba(240,122,181,0.08)',         // was rgba(240,122,181,0.07) — gallery L105
  roseBorder: 'rgba(240,122,181,0.22)',     // was rgba(240,122,181,0.26) — gallery L105
  roseDim: '#c98caa',                       // gallery L105
  gold: '#eab36a',                          // gallery L108,L230,L234,L276
  goldDim: 'rgba(234,179,106,0.2)',         // UNVERIFIED alpha — gallery renders the pair as a .15→.05 gradient
  text: '#eef3fb',                          // gallery L82,L89,L104,L109,L111,L223,L275
  dim: '#93a0b8',                           // gallery L90,L103,L108,L253,L274
  dimmer: '#6f7a92',                        // was #63708c — gallery L101,L226,L240,L250,L259,L272,L284,L291
  blue: '#3aa0da',                          // was #49ade0 — gallery L102,L103; see RECONCILIATION §Ambiguities
  green: '#4fd69a',                         // gallery L109,L111,L228,L236,L268,L293
  amber: '#eab36a',                         // gallery L108,L276
  teal: '#45cfc0',                          // was #56c9d6 — gallery L245; see RECONCILIATION §Ambiguities
  purple: '#b98aec',                        // UNVERIFIED — no hardware 4c/5c occurrence
  orange: '#e2915a',                        // UNVERIFIED — no hardware 4c/5c occurrence
  red: '#ef7683',                           // was #ff6b6b — gallery L255,L288
  strategy: '#d071d8',                      // was #df7ad0 — gallery L246
  horizon: '#8fa6c8',                       // UNVERIFIED — no gallery occurrence
  side: '#9aa0e0',                          // was #7f97d6 — gallery L231 (hardware reuses the celestial side hue)
  sig: '#58c4e6',                           // gallery L82,L86,L94,L108,L222,L223,L243,L261,L264,L280
  on: '#07080f',                            // was #04060c — gallery L223 (badge label on a solid sig fill)
  onGreen: '#07120e',                       // was #04160f — gallery L236,L268,L293
  box: 'rgba(0,0,0,0.3)',                   // was rgba(0,0,0,0.4) — gallery L263 (segmented well)
  inkBg: 'rgba(0,0,0,0.35)',                // was rgba(0,0,0,0.38) — gallery L119,L275,L280
  inkBorder: 'rgba(255,255,255,0.1)',       // gallery L119,L280
  actBg: 'rgba(234,179,106,0.15)',          // was rgba(234,179,106,0.14) — gallery L108,L276
  actBorder: 'rgba(234,179,106,0.4)',       // gallery L108,L276
  textSoft: '#c5cddd',                      // NEW — gallery L242-246
  dim2: '#7f8aa2',                          // NEW — gallery L82,L89,L95-97,L109,L254,L265-266,L277-278
  dimmest: '#5f6a86',                       // NEW — gallery L111,L119,L262,L268,L280
  disabled: '#454e68',                      // NEW — gallery L109
};

const hwStar =
  'linear-gradient(0deg,rgba(255,255,255,.014) 1px,transparent 1px),' +
  'linear-gradient(90deg,rgba(255,255,255,.014) 1px,transparent 1px)';

const hwAmbient =
  'radial-gradient(120% 55% at 85% 0%,rgba(222,80,170,.14),transparent 55%),' +
  'radial-gradient(120% 60% at 5% 100%,rgba(40,160,210,.16),transparent 55%)';

const hwEffects: ThemeEffects = {
  bevelHighlight: 'inset 0 1px 0 rgba(255,255,255,0.08)',          // gallery L90,L228-231
  bevelHighlightStrong: 'inset 0 1px 0 rgba(255,255,255,0.13)',    // gallery L252
  bevelShadow: 'inset 0 -1px 0 rgba(0,0,0,0.32)',                  // gallery L252,L253
  bevelInset: 'inset 0 1px 2px rgba(0,0,0,0.4)',                   // gallery L263,L275
  bevelInsetDeep: 'inset 0 1px 3px rgba(0,0,0,0.4)',               // gallery L119,L280
  containerHighlight: 'inset 0 1px 0 rgba(255,255,255,0.05)',      // gallery L221
  containerShadow: '0 34px 90px rgba(0,0,0,0.62)',                 // gallery L221
  paneShadow: '0 16px 34px rgba(0,0,0,0.55)',                      // gallery L285
  glassFill: 'linear-gradient(180deg,rgba(255,255,255,0.05),rgba(255,255,255,0.01))', // gallery L116,L253
  glassFillFaint: 'rgba(255,255,255,0.03)',                        // gallery L95-97,L277
  glassBorder: '1px solid rgba(255,255,255,0.07)',                 // gallery L221
  topAccent: 'linear-gradient(90deg,#f593c1,#58c4e6)',             // gallery L222 — v4 used a transparent→blue→transparent ramp
  topAccentHeight: '2px',                                          // gallery L222 — v4 used 1px for hardware
  topAccentGlow: 'none',                                           // gallery L222 carries no glow
  star: hwStar,                                                    // NEW — 26px instrument grid; v4 hardware `star` was ''
  ambient: hwAmbient,                                              // gallery L84
  glowSm: (c) => `0 0 7px ${alpha(c, 0.7)}`,                        // gallery L242-246
  glowLg: (c) => `0 0 4px ${alpha(c, 0.85)},0 0 10px 2px ${alpha(c, 0.45)}`, // gallery L103,L108
  glowRing: (c) => `0 0 3px ${alpha(c, 0.6)},0 0 9px 1px ${alpha(c, 0.4)},inset 0 0 4px ${alpha(c, 0.3)}`, // gallery L111
  glowText: (c) => `0 0 3px ${alpha(c, 0.9)},0 0 9px ${alpha(c, 0.65)}`,     // gallery L109
  glowToast: (c) => `0 0 16px ${alpha(c, 0.45)}`,                   // gallery L293
  glowButton: (c) => `0 0 14px ${alpha(c, 0.2)}`,                   // gallery L115,L252
};

// ─── Themes ──────────────────────────────────────────────────────────────────

export const themes: Record<ThemeName, Theme> = {
  celestial: {
    name: 'celestial',
    mode: 'celestial',
    label: 'Celestial',
    tag: 'space-girl future femme',
    chip: 'soft',
    font: "'Sora',-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif",
    mono: MONO,
    r: {
      chip: '999px',
      card: '16px',                 // UNVERIFIED — gallery celestial cards are borderless; nearest evidence is 13px (L55) / 14px (L203)
      field: '999px',               // was 13px — gallery L193,L194-196,L198 (celestial fields are pills)
      ctl: '999px',                 // was 11px — gallery L146-154,L179-184
      mod: '14px',                  // was 18px — gallery L203 (menu)
    },
    chrome: 'rgba(12,8,22,0.4)',    // UNVERIFIED — gallery L39-43 header is transparent over the starfield
    blur: 'blur(22px) saturate(1.4)',
    pane: 'rgba(30,20,32,0.92)',    // was rgba(10,7,19,0.58) — gallery L203 (menu surface)
    paneBlur: 'blur(30px) saturate(1.35)',
    star: celStar,
    c: cel,
    effects: celEffects,
  },
  hardware: {
    name: 'hardware',
    mode: 'hardware',
    label: 'Hardware',
    tag: 'cyberdeck hacker future femme',
    chip: 'hard',
    font: "'Space Grotesk',-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif",
    mono: MONO,
    r: {
      chip: '3px',                  // was 4px — gallery L228-231,L268,L276
      card: '5px',                  // was 6px — gallery L102,L107,L285
      field: '3px',                 // was 5px — gallery L264,L275,L277
      ctl: '4px',                   // was 5px — gallery L94-97,L119,L252,L280
      mod: '5px',                   // was 6px — gallery L285
    },
    chrome: 'linear-gradient(180deg,rgba(20,24,38,0.7),rgba(10,12,22,0.7))', // was linear-gradient(180deg,rgba(19,23,36,0.94),rgba(9,11,20,0.94)) — gallery L88
    blur: 'none',
    pane: 'rgba(10,13,22,0.96)',    // was #090b13 — gallery L285
    paneBlur: 'none',
    star: hwStar,                   // was '' — gallery L221 instrument grid
    c: hw,
    effects: hwEffects,
  },
};

/** Card/panel background: hardware panels are a gradient, celestial are flat. */
export function panelBackground(mode: ThemeName): string {
  return mode === 'hardware'
    ? 'linear-gradient(180deg,rgba(18,22,34,0.66),rgba(10,12,20,0.66))' // gallery L102,L107
    : themes.celestial.c.panel;
}

/**
 * Object-type colors. AUTHORITATIVE — this is an explicit legend in the gallery, not
 * an inference. Heading, celestial: `Object types · structure ramp + kinds` (L158);
 * hardware mirror: `// object types · structure ramp + kinds` (L240).
 *
 * WHAT THE HEADING MEANS, and why it supersedes v4's TYPE map:
 *
 *   "structure ramp" — Goal ⊃ Project ⊃ Task is the containment hierarchy, and it gets a
 *   CONTINUOUS pale-cyan → cyan → blue ramp. Depth reads off the hue directly.
 *   "kinds"          — Recurring and Strategy sit OUTSIDE that hierarchy, so they get
 *   distinct off-ramp hues rather than a position on it.
 *
 * v4's TYPE map (GOAL:amber, PROJECT:blue, TASK:green, RECURRING:orange) is superseded.
 * It had no ramp, and — more seriously — it colored TASK green, which collides with the
 * completion green used for done/steady/saved everywhere in the gallery (verified: every
 * green occurrence in the trusted regions is a ✓, a checkbox, a "Steady" tag or a "Saved"
 * toast; zero sit on a task row). The gallery deliberately keeps Recurring's green-teal a
 * different hex from completion green for the same reason.
 *
 * Depth is expressed by INDENTATION, never by hue: the nested children in the phone
 * mockups carry status glyph colors only, no type-ramp accent.
 */
export const typeRamp: Record<ThemeName, Record<string, string>> = {
  // gallery L160-164 (legend, verbatim)
  celestial: {
    GOAL: '#9fe0e8',
    PROJECT: '#5fc6d6',
    SUBPROJECT: '#4faad3', // ⚠ INFERRED — no legend entry; midpoint of PROJECT→TASK on the ramp
    WORKSTREAM: '#a98fee', // ⚠ INFERRED — no legend entry; observed in 4a L59, off-ramp purple
    TASK: '#3f8fd0',
    RECURRING: '#4fb8a6',
    STRATEGY: '#d58fd8',
  },
  // gallery L242-246 (legend, verbatim)
  hardware: {
    GOAL: '#9be2f0',
    PROJECT: '#58c4e6',
    SUBPROJECT: '#53a1e6', // ⚠ INFERRED — midpoint of PROJECT→TASK
    WORKSTREAM: '#a98fee', // ⚠ INFERRED — no hardware observation; celestial value carried over
    TASK: '#4f7fe6',
    RECURRING: '#45cfc0',
    STRATEGY: '#d071d8',
  },
};

/**
 * ⚠ TWO OPEN ITEMS on the ramp above, both flagged rather than silently resolved:
 *
 * 1. SUBPROJECT and WORKSTREAM have NO legend entry — the gallery lists five types, the app
 *    has seven. Subproject is interpolated on the ramp (it sits between Project and Task in
 *    containment). Workstream is taken from an off-legend purple observed in the celestial
 *    phone mockup; `docs/map_design.md:119` requires workstreams render structurally distinct
 *    from projects, which an interpolated ramp value would NOT satisfy — hence off-ramp.
 *
 * 2. The phone mockups are legend-INCONSISTENT and must not be used to override the legend.
 *    Celestial gives "Job search" the legend's Project cyan; hardware gives the same object an
 *    off-legend `#3aa0da` and gives "Scholarly writing" the legend's Project cyan instead.
 *    They agree only that depth is not colored. Treat 5a/5c as the legend, 4a/4c as decorative.
 */

export default themes;
