/**
 * Schema derivation. Ported from `applySchema()` ~line 126 of
 * design/mockups/review-reorganize-mobile-v4.html.
 *
 * v4:
 *   applySchema(){ const S=this.SCHEMA;
 *     this.OPTS=Object.fromEntries(Object.entries(S.relations)
 *       .map(([k,r])=>[k,(r.options||[]).slice()]));
 *     this.CTRL=S.controls; this.TEXT=S.notes; }
 *
 * Every select, chip menu, toggle, date picker, number field, recurrence editor
 * and notes textarea in the detail pane is generated by iterating these three.
 * There is no hardcoded form anywhere — a wrong schema produces an empty UI,
 * not a degraded one (api_contract_v2 §3.1).
 */

import type { Schema, RelationKey } from '../fixtures/index.ts';
import type { DerivedSchema } from './types.ts';

export function applySchema(schema: Schema): DerivedSchema {
  const OPTS = Object.fromEntries(
    Object.entries(schema.relations).map(([k, r]) => [k, (r.options || []).slice()]),
  ) as Record<RelationKey, string[]>;

  // CTRL and TEXT are passed through by reference in v4, not copied. Kept that
  // way: the schema literal is treated as immutable by every reader.
  return { OPTS, CTRL: schema.controls, TEXT: schema.notes };
}
